Import libraries

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
#%matplotlib inline
import pandas as pd
import math
import numpy as np
from datetime import datetime, timedelta
from scipy import stats
import warnings
from IPython.display import display
import ipywidgets as widgets
pd.options.mode.chained_assignment = None 
from datetime import timezone
import datetime
from suntime import Sun
import pytz
from numpy.linalg import norm
from sklearn.metrics.pairwise import cosine_similarity

Read CSV

In [3]:
dataset = pd.read_csv("10sec-original.csv")

dataset['datetime'] = pd.to_datetime(dataset['datetime'], format='mixed')
lat = 18.47
lon = -66.12
tz = pytz.timezone('America/Puerto_Rico')

In [4]:
dataset

      tagID                datetime     event
0      1621 2017-06-21 08:00:10.850  entering
1      1621 2017-06-21 08:10:33.850   exiting
2      1621 2017-06-21 08:24:48.250  entering
3      1621 2017-06-21 08:51:23.450  entering
4      1621 2017-06-21 08:55:48.300   exiting
...     ...                     ...       ...
1855    661 2017-06-22 17:09:08.250  entering
1856   2258 2017-06-22 11:49:10.700  entering
1857   2258 2017-06-22 12:07:42.750   exiting
1858   2258 2017-06-22 16:14:06.350  entering
1859   2258 2017-06-24 11:52:27.800  entering

[1860 rows x 3 columns]

Data cleaning functions

Separate entry/exit events and convert into flights, takes entry/exit dataset
for a single bee and returns a table.

In [5]:

def classifyLoc(dataset):

    bee = dataset
    
    cur = bee['event']
    nxt = cur.shift(-1)
    cur_dt = bee['datetime']
    nxt_dt = cur_dt.shift(-1)
    #selects all except last
    valid = nxt.notna()
    location = np.select(
        [
            (cur == "entering") & (nxt == "exiting"),
            (cur == "entering") & (nxt == "exiting-entering"),
            
            (cur == "entering-exiting") & (nxt == "entering"),
            (cur == "exiting") & (nxt == "entering"),
            (cur == "exiting") & (nxt == "entering-exiting"),
            
            (cur == "entering") & (nxt == "entering"),
            (cur == "outside") & (nxt == "outside"),
        ],
        ["Inside", "Inside", "Outside", "Outside", "Outside", "Unknown-Inside", "Outside-Unknown"],
        default="Unknown",
    )
            
    t0 = cur_dt.iloc[0]
    age = (cur_dt - t0).dt.days

    #new dataset with inside/outside and time start/end
    BeeTravel = pd.DataFrame(
        {
            "location": location[valid],
            "start": cur_dt[valid],
            "end": nxt_dt[valid],
            "age": age[valid]
        }
    ).reset_index(drop=True)
    
    #classify short outside/insides as part of another group
    BeeTravel['activity'] = "undefined"
    BeeTravel.loc[BeeTravel["location"] == "Inside", "activity"] = "inside"
    duration = (BeeTravel["end"] - BeeTravel["start"]).dt.total_seconds()
    outside = BeeTravel["location"].isin(["Outside"])
   
    #Classify outside flights depending on length
    BeeTravel.loc[outside & (duration < 300), "activity"] = "outside-short"
    BeeTravel.loc[outside & (duration >= 300) & (duration  < 7200), "activity"] = "outside-foraging"
    BeeTravel.loc[outside & (duration >= 7200), "activity"] = "outside-long"
    BeeTravel['tagID'] = dataset['tagID'].iloc[0]

    return BeeTravel

Utilizes the previous function on every individual bee to have a full table.

In [6]:
def cleanData(data):

    activity = []
    
    allActivity = (
        data.sort_values(["tagID","datetime"])
        .groupby("tagID", group_keys = False)[data.columns]
        .apply(classifyLoc)
        .reset_index(drop=True)
    )
    
    
    df = (allActivity[allActivity['location'].isin(["Outside","Outside-Unknown"])]
        [["tagID","start","end"]]
        .rename(columns={'start':'tripStart','end':'tripEnd'})
        .copy()
    )
     
     
    df['duration'] = df['tripEnd'] - df['tripStart']

    return allActivity, df

In [7]:
def fixHourMin(duration):
    hour = int(duration.total_seconds() // 3600)
    mins = int(duration.total_seconds() // 60 % 60)
    if mins < 10:
        mins = f'0{mins}'
    return f'{hour}:{mins}'

Creates a statistical summary of an entire hive based on two tables, all activity and all flights.
Returns a table containing the statistical summary.

Does so by iterating over every beeID separately.

In [8]:
def summaryData(activity,flights):
    
    
    seen = activity.groupby("tagID").agg(
        firstSeen = ('start','min'),
        lastSeen = ('end','max')
    )
    
    seen['firstSeen'] = seen['firstSeen'].dt.floor("s")
    seen['lastSeen'] = seen['lastSeen'].dt.floor("s")
    
    indFlight = flights.groupby("tagID").agg(
        firstFlight = ('tripStart','min'),
        lastFlight = ('tripStart','max'),
        avgTrip = ('duration','mean'),
        medianTrip = ('duration','median'),
        numTrips = ('duration','size')
    )
    
    indFlight['firstFlight'] = indFlight['firstFlight'].dt.floor("s").apply(lambda x: x.strftime('%Y-%m-%d ~ %H:%M:%S'))
    indFlight['lastFlight'] = indFlight['lastFlight'].dt.floor("s").apply(lambda x: x.strftime('%Y-%m-%d ~ %H:%M:%S'))
    indFlight['avgTrip'] = indFlight['avgTrip'].map(fixHourMin)
    indFlight['medianTrip'] = indFlight['medianTrip'].map(fixHourMin)
    
    tpd = flights.groupby("tagID").size().rename("tripsPerDay")
    
    full = seen.join(indFlight, how="left").join(tpd, how="left")
    full["tripsPerDay"].fillna(0, inplace = True)
      
    divisor = (full['lastSeen'].dt.date - full['firstSeen'].dt.date).apply(lambda x: x.days) + 1
    full['tripsPerDay'] = full["tripsPerDay"]/divisor
    full['tripsPerDay'] = full["tripsPerDay"].apply(lambda x: x if x > 0 else None)
    
    full['firstSeen'] = full['firstSeen'].apply(lambda x: x.strftime('%Y-%m-%d ~ %H:%M:%S'))
    full['lastSeen'] = full['lastSeen'].apply(lambda x: x.strftime('%Y-%m-%d ~ %H:%M:%S'))
    longest = flights.groupby('tagID')['duration'].idxmax()
    shortest = flights.groupby('tagID')['duration'].idxmin()
    
    long_df = flights.loc[longest, ["tagID", "tripStart", "duration"]].set_index("tagID")
    short_df = flights.loc[shortest, ["tagID", "tripStart", "duration"]].set_index("tagID")
    
    long_str = (
        long_df["tripStart"].dt.floor("s").astype(str)
        + " ~ "
        + long_df["duration"].map(fixHourMin)
    ).rename("longestFlight")
    
    short_str = (
        short_df["tripStart"].dt.floor("s").astype(str)
        + " ~ "
        + short_df["duration"].map(fixHourMin)
    ).rename("shortestFlight")
    
    full = full.join(long_str, how="left").join(short_str, how="left")
    
    beeSummary = full.rename(columns={"firstSeen":"First Seen", "lastSeen":"Last Seen","firstFlight":"First Flight",
                            "lastFlight":"Last Flight", "longestFlight":"Longest Flight","shortestFlight":"Shortest Flight",
                            "avgTrip":"Average Flight Duration", "numTrips":"# of Flights","tripsPerDay":"Average Flights per Day", "medianTrip":"Median Flight Duration"})
    beeSummary = beeSummary.reset_index()

    return beeSummary

Total summary table creation with values of all hive.

In [9]:
def makeTotalSum(flights):
    #general overview
    totalFlights = len(flights)
    flights['day'] = flights['tripStart'].apply(lambda x: x.date())
    totalPerDay = flights['day'].value_counts().mean()
    totalLength = flights['duration'].mean()
    totalLength = totalLength.total_seconds()/60

    #longest and shortest flights
    longest = flights['duration'].idxmax()
    shortest = flights['duration'].idxmin()

    longestDate = flights.loc[longest]['tripStart'].strftime('%Y-%m-%d ~ %H:%M:%S')
    longestID = flights.loc[longest]['tagID']
    longestLen = flights.loc[longest]['duration'].total_seconds()/60

    shortestDate = flights.loc[shortest]['tripStart'].strftime('%Y-%m-%d ~ %H:%M:%S')
    shortestID = flights.loc[shortest]['tagID']
    shortestLen = flights.loc[shortest]['duration'].total_seconds()/60

    #create tables
    #general info
    totalDict = {"Total Flights":totalFlights, "Avg Flights per Day":totalPerDay, "Avg Length per Day (minutes)":totalLength}
    totalSum = pd.DataFrame.from_dict(totalDict, orient='index')
    totalSum = totalSum.rename(columns={0: "Overall Statistics"})

    #info on longest/shortest trip
    tripDict = {"Classification":["Longest Flight", "Shortest Flight"],"Date":[longestDate, shortestDate], "BeeID":[longestID, shortestID], "Length (minutes)":[longestLen, shortestLen]}
    tripSum = pd.DataFrame.from_dict(tripDict)
    
    return totalSum, tripSum

Obtain sunrise and sunset table for actograph based on previously defined timezone and required days for table.

In [10]:
def getSRSS(dataset, tz, lat, lon):
    dates = dataset['start'].apply(lambda x: x.date()).sort_values()
    dates = dates.unique()
    sunrise = []
    sunset = []
    sun = Sun(lat, lon)
    for d in dates:
        dT = datetime.datetime(d.year, d.month, d.day)
        sunrise.append(sun.get_sunrise_time(dT).astimezone(tz).time())
        sunset.append(sun.get_sunset_time(dT).astimezone(tz).time())

    srss = pd.DataFrame.from_dict({"date":dates,"sunrise":sunrise,"sunset":sunset})
    return srss

Split overnight flights at midnight for plotting reasons

missing = True and timeam/timepm for when a dataset has missing values depending
on dataset requirement.

In [11]:
def separateFlights(flights,missing=False,timeam="08:00:00",timepm="18:00:00"):
    newdata = []
    
    for i in range(len(flights)):
        row = flights.iloc[i].copy()
        row['day'] = row['tripStart'].to_pydatetime().day
        day = row['day']
        month0 = row['tripStart'].to_pydatetime().month
        month1 = row['tripEnd'].to_pydatetime().month
        
        if row['tripStart'].to_pydatetime().day != row['tripEnd'].to_pydatetime().day:
            #first day
            newentry = row.copy()
            newentry['tripEnd'] = row['tripEnd'].replace(hour=23,minute=59,second=59,day=1,month=1)
            newentry['tripStart'] = row['tripStart'].replace(day=1,month=1)
            newentry['date'] = fixDate(row['tripStart'])
            newdata.append(newentry)
            #second day
            newday = row['tripEnd'].to_pydatetime().day
            newentry = row.copy()
            newentry['tripStart'] = row['tripStart'].replace(day=1,hour=0,minute=0,second=0,month=1)
            newentry['tripEnd'] = row['tripEnd'].replace(day=1,month=1)
            newentry['day'] = newday
            newentry['date'] = fixDate(row['tripEnd'])
            newdata.append(newentry)
        else:
            newentry = row.copy()
            newentry['tripStart'] = row['tripStart'].replace(day=1,month=1)
            newentry['tripEnd'] = row['tripEnd'].replace(day=1,month=1)
            newentry['date'] = fixDate(row['tripStart'])
            newdata.append(newentry)

    if missing:
        cutoffday = str(newentry['tripStart'].date())
        #Extra for missing dataset
        for i in range(len(newdata)):
            cutoffpm = datetime.strptime(cutoffday + " " + timepm,"%Y-%m-%d %H:%M:%S")
            cutoffam = datetime.strptime(cutoffday + " " + timeam,"%Y-%m-%d %H:%M:%S")
            if newdata[i]['tripEnd'] >= cutoffpm:
                newrow = newdata[i].copy()
                newdata[i]['tripEnd'] = cutoffpm
                newdata[i]['Data'] = 'Available'
                newrow['tripStart'] = cutoffpm
                newrow['Data'] = 'Missing'
                newdata.append(newrow)
            elif newdata[i]['tripStart'] <= cutoffam:
                newrow = newdata[i].copy()
                newdata[i]['tripStart'] = cutoffam
                newdata[i]['Data'] = 'Available'
                newrow['tripEnd'] = cutoffam
                newrow['Data'] = 'Missing'
                newdata.append(newrow)
            else:
                newdata[i]['Data'] = "Available"
    else:
        for i in range(len(newdata)):
            newdata[i]['Data'] = 'Available'
    
    
    flights_mod = pd.concat(newdata, axis = 1)
    flights_mod = flights_mod.transpose().reset_index()
    flights_mod = flights_mod.drop(["index"],axis=1)
    return flights_mod

Apply shapes to time graph based on sunrise/sunset dataset.

Create time plot for bee flights utilizing flights dataset.

In [12]:
#function to change hour column into hour properly

def fixTime(hr):
    if hr < 10:
        return "0" + str(hr) + ":00"
    else:
        return str(hr) + ":00"
        
#function to change date column appropriately

def fixDate(x):
    if x.day > 9 and x.month > 9:
        return f'{x.month}/{x.day}'
    elif x.day > 9 and x.month < 10:
        return f'0{x.month}/{x.day}'
    elif x.day < 10 and x.month > 9:
        return f'{x.month}/0{x.day}'
    else:
        return f'0{x.month}/0{x.day}'

Prepare all new datasets based on csv

In [13]:
allActivity, flights = cleanData(dataset)
beeSummary = summaryData(allActivity,flights)
dt = getSRSS(allActivity, tz, lat, lon)
dt['date'] = dt['date'].apply(lambda x: fixDate(x))
Summary0, Summary1 = makeTotalSum(flights)


flights['date'] = flights['tripStart'].apply(lambda x: fixDate(x))
flights['hour'] = flights['tripStart'].apply(lambda x: x.hour)
flights['day'] = flights['tripStart'].apply(lambda x: x.day)
flights_mod = separateFlights(flights)

In [14]:
flights

,tagID,tripStart,tripEnd,duration,day,date,hour
1,197,2017-06-21 08:11:24.300,2017-06-21 08:28:03.650,0 days 00:16:39.350000,21,06/21,8
3,197,2017-06-21 08:37:01.650,2017-06-21 08:58:19.050,0 days 00:21:17.400000,21,06/21,8
7,197,2017-06-21 11:36:20.200,2017-06-21 13:10:58.100,0 days 01:34:37.900000,21,06/21,11
20,197,2017-06-22 16:13:54.750,2017-06-24 09:07:51.850,1 days 16:53:57.100000,22,06/22,16
22,197,2017-06-24 10:24:33.900,2017-06-24 15:44:37.050,0 days 05:20:03.150000,24,06/24,10
...,...,...,...,...,...,...,...
1813,2487,2017-06-22 08:23:36.650,2017-06-22 09:18:19.850,0 days 00:54:43.200000,22,06/22,8
1818,2487,2017-06-22 13:10:09.450,2017-06-22 15:16:52.900,0 days 02:06:43.450000,22,06/22,13
1821,2487,2017-06-23 09:08:55.000,2017-06-23 09:38:04.300,0 days 00:29:09.300000,23,06/23,9
1825,2487,2017-06-24 08:36:48.600,2017-06-24 09:49:40.550,0 days 01:12:51.950000,24,06/24,8
1827,2487,2017-06-24 10:24:33.700,2017-06-24 10:25:52.750,0 days 00:01:19.050000,24,06/24,10

Divide bees in day-focus/afternoon-focus

In [15]:
def divideBees(dataset):
    hour = dataset['hour'].unique()
    hour.sort()
    split = np.where(hour == 12)[0][0]
    final = {"morning":[],"afternoon":[],"even":[]}
    vectors = {}
    maxcount = dataset[['tagID','hour']].value_counts().max()
    divisor = 10 ** math.ceil(math.log10(maxcount))
    #print(split)
    for i in dataset['tagID'].unique():
        bee = dataset[dataset['tagID'] == i]
        data, bins = np.histogram(bee['hour'], bins=hour,density=True)
        vector = bee['hour'].value_counts().reindex(hour, fill_value=0)
        vector = vector.sort_index()
        vector = vector/divisor
        #print(i)
        #print(data)
        morning = sum(data[0:split])
        afternoon = sum(data[split:])
        if morning > 0.7:
            final['morning'].append(i)
        elif afternoon > 0.7:
            final['afternoon'].append(i)
        else:
            final['even'].append(i)

        vectors[str(i)] = vector.tolist()

    return final,vectors
        

division, vectors = divideBees(flights)

Cosine similarity for collapsed vectors

In [16]:
threshold1 = 0.8
def findSimilar(vectors, tagID):
    similars = []
    current = vectors[str(tagID)]
    for key,value in vectors.items():
        A = value
        B = current
        cosine = np.dot(A, B) / (norm(A) * norm(B))
        if cosine > threshold1:
            similars.append(key)
    return(similars)

findSimilar(vectors,1621)

['197', '508', '1237', '1361', '1621', '1780', '2487']

In [17]:
#matrix for every day where 1 = activity, 0 = no activity (matrixes_simp)
#matrix where each value is % of hour spent outside (matrixes)


def createMatrix(df):
    df = df.copy()

    df.sort_values(by='date')
    df['day'] = df['date'].astype('category').cat.codes
    df['tripStart'] = pd.to_datetime(df['tripStart'])
    df['tripEnd']   = pd.to_datetime(df['tripEnd'])
    df['start_hour'] = df['tripStart'].dt.hour
    df['end_hour'] = df['tripEnd'].dt.hour

    n_days = df['day'].nunique()

    result = {}
    result_simple = {}
    result_count = {}

    for tag, g in df.groupby('tagID'):
        matrix = np.zeros((n_days, 24))
        matrix_simple = np.zeros((n_days, 24))
        matrix_count = np.zeros((n_days, 24))

        for index, row in g.iterrows():
            matrix_simple[row.day, row.start_hour:row.end_hour+1] = 1
            matrix_count[row.day, row.start_hour] += 1
            start_h = row.tripStart.hour
            end_h   = row.tripEnd.hour

            for h in range(start_h, end_h + 1):
                hour_start = row.tripStart.floor('D') + pd.Timedelta(hours=h)
                hour_end   = hour_start + pd.Timedelta(hours=1)

                overlap = (
                    min(row.tripEnd, hour_end)
                    - max(row.tripStart, hour_start)
                ).total_seconds()

                if overlap > 0:
                    matrix[row.day, h] += overlap / 3600

                    
        result[str(tag)] = matrix
        result_simple[str(tag)] = matrix_simple
        result_count[str(tag)] = matrix_count

    return result, result_simple, result_count
            
matrixes, matrixes_simp, matrixes_count = createMatrix(flights)

bin size experimentation

In [18]:
#flatten matrix and find cosine similarity of flattened matrix (vector)
threshold2 = 0.6
flattened = {}
for k in matrixes:
    flat = matrixes[k].copy()
    flat = flat.flatten()
    flattened[k] = flat

def findSimilarMatrix(vectors, tagID):
    similars = []
    current = vectors[str(tagID)]
    for key,value in vectors.items():
        A = value
        B = current
        cosine = np.dot(A, B) / (norm(A) * norm(B))
        if cosine > threshold2:
            similars.append(key)
    return(similars)
    
findSimilarMatrix(flattened,1621)

['1361', '1621']

In [19]:
#find cosine similarity of each day's vector, and then get score from how many days are similar
def findSimilarDay(matrixes, tagID, threshold):
    similars = []
    current = matrixes[str(tagID)]
    for key,value in matrixes.items():
        A = value
        B = current
        #count of all cosine similarities
        Acount = []
        for day in range(len(A)):
            Avec = A[day]
            Bvec = B[day]
            if norm(Avec) == 0 and norm(Bvec) == 0:
                Acount.append(1)
                continue
            elif (norm(Avec) * norm(Bvec)) == 0:
                Acount.append(0)
                continue
            cosine = np.dot(Avec, Bvec) / (norm(Avec) * norm(Bvec))
            if cosine >= threshold:
                Acount.append(1)
            else:
                Acount.append(0)
        if sum(Acount)/len(Acount) >= threshold:
            similars.append(key)
    return(similars)

findSimilarDay(matrixes_simp,1621,0.7)

['1361', '1621']

In [20]:
#find cosine similarity of each day's vector, and then get score from how many days are similar
def findSimilarDay(matrixes, tagID, threshold):
    similars = []
    current = matrixes[str(tagID)]
    for key,value in matrixes.items():
        A = value
        B = current
        #count of all cosine similarities
        Acount = []
        for day in range(len(A)):
            Avec = A[day]
            Bvec = B[day]
            if norm(Avec) == 0 and norm(Bvec) == 0:
                Acount.append(1)
                continue
            elif (norm(Avec) * norm(Bvec)) == 0:
                Acount.append(0)
                continue
            cosine = np.dot(Avec, Bvec) / (norm(Avec) * norm(Bvec))
            if cosine >= threshold:
                Acount.append(1)
            else:
                Acount.append(0)
        if sum(Acount)/len(Acount) >= threshold:
            similars.append(key)
    return(similars)

findSimilarDay(matrixes,1621,0.7)

['1361', '1621']

In [21]:
def similarFroNorm(matrixes,tagID):
    similars = []
    current = matrixes[str(tagID)]
    for key,value in matrixes.items():
        dif = (current - value)
        n = norm(dif, ord="fro")
        print(key)
        print(n/norm(current,ord="fro"))

print("TIME MATRIX")
similarFroNorm(matrixes,1621)
print("ACTIVITY MATRIX")
similarFroNorm(matrixes_simp,1621)

TIME MATRIX
197
1.14135901106947
508
1.1492148004768075
515
1.248321064240831
516
0.9982112363355458
517
1.047056029599802
638
0.9301910133096223
661
1.0851031801410649
677
0.9683506832625238
930
1.010970740392928
1230
0.9169514980541443
1237
1.22627283149459
1361
1.0884964776682968
1404
1.0069826538839097
1407
1.036153225578213
1415
1.002021507016564
1607
1.057124284736037
1609
1.053216769170626
1621
0.0
1651
0.9999086837955651
1652
1.0540116520124556
1698
0.997143822781802
1722
1.1773292391693118
1780
1.0859047168319231
1786
1.066524506286424
1797
1.1319287257444481
1900
0.9994981680195144
1979
1.0000528028395235
2258
1.1529928906592364
2487
1.0668308421184136
ACTIVITY MATRIX
197
1.0339078862458586
508
1.0170952554312156
515
1.1141720290623112
516
1.0504514628777806
517
1.1596670152276025
638
0.9284766908852594
661
1.0667385033281394
677
0.909717652294684
930
0.909717652294684
1230
0.9284766908852594
1237
1.1596670152276025
1361
0.8709883407113855
1404
0.9649012813540154
1407
1.0985884360051028
1415
0.9468641529479986
1607
1.259447059844805
1609
1.0339078862458586
1621
0.0
1651
1.0
1652
1.0504514628777806
1698
1.0827805840074196
1722
1.0985884360051028
1780
1.1744404390294072
1786
1.0170952554312156
1797
1.1295406451144276
1900
1.0504514628777806
1979
1.0170952554312156
2258
1.0827805840074196
2487
0.9468641529479986

In [22]:
def similarSpecNorm(matrixes,tagID):
    similars = []
    current = matrixes[str(tagID)]
    for key,value in matrixes.items():
        dif = current - value
        n = norm(dif, ord=2)
        print(key)
        print(n/norm(current, ord=2))

similarSpecNorm(matrixes,1621)

197
1.1375623059542816
508
1.0429719175906194
515
1.145845909957538
516
0.9956182975762087
517
0.9426270116094005
638
0.865573650665705
661
0.981428088808476
677
0.8952873994738805
930
0.9597841349539907
1230
0.9156596695102815
1237
1.1830430571980541
1361
1.1123697010527813
1404
0.9865892223291918
1407
0.9659577068493876
1415
0.9170145872257528
1607
0.9598800615876958
1609
0.9558309913699674
1621
0.0
1651
0.9971143132466597
1652
0.9579312690179217
1698
0.9937932977744129
1722
1.0445971909638023
1780
1.0361951846845432
1786
0.8931897020749682
1797
1.0559209499496267
1900
0.9973748284713884
1979
0.9983537593170445
2258
1.0339659987579037
2487
0.8999157857033094

In [23]:
flights['duration'].mean()

Timedelta('0 days 01:01:08.235208711')

In [24]:
flights['duration'].median()

Timedelta('0 days 00:02:58.750000')

In [25]:
flights['duration'].std()

Timedelta('0 days 03:57:49.516563168')

In [26]:
allActivity['duration'] = (allActivity['end'] - allActivity['start']).apply(lambda x: x.total_seconds())
allActivity['day'] = allActivity['start'].dt.day
allActivity['daydiff'] = (allActivity['end'].dt.day - allActivity['start'].dt.day)
dormant = allActivity[(allActivity['location'] == "Inside") & (allActivity['daydiff'] == 0)]
flights = allActivity[(allActivity['location'] == "Outside") & (allActivity['daydiff'] == 0)]
flights['date'] = flights['start'].apply(lambda x: fixDate(x))

In [27]:
flights

,location,start,end,age,activity,tagID,duration,day,daydiff,date
1,Outside,2017-06-21 08:11:24.300,2017-06-21 08:28:03.650,0,outside-foraging,197,999.35,21,0,06/21
3,Outside,2017-06-21 08:37:01.650,2017-06-21 08:58:19.050,0,outside-foraging,197,1277.40,21,0,06/21
7,Outside,2017-06-21 11:36:20.200,2017-06-21 13:10:58.100,0,outside-foraging,197,5677.90,21,0,06/21
22,Outside,2017-06-24 10:24:33.900,2017-06-24 15:44:37.050,3,outside-long,197,19203.15,24,0,06/24
23,Outside,2017-06-21 10:20:14.450,2017-06-21 12:15:25.800,0,outside-foraging,508,6911.35,21,0,06/21
...,...,...,...,...,...,...,...,...,...,...
1813,Outside,2017-06-22 08:23:36.650,2017-06-22 09:18:19.850,0,outside-foraging,2487,3283.20,22,0,06/22
1818,Outside,2017-06-22 13:10:09.450,2017-06-22 15:16:52.900,1,outside-long,2487,7603.45,22,0,06/22
1821,Outside,2017-06-23 09:08:55.000,2017-06-23 09:38:04.300,1,outside-foraging,2487,1749.30,23,0,06/23
1825,Outside,2017-06-24 08:36:48.600,2017-06-24 09:49:40.550,2,outside-foraging,2487,4371.95,24,0,06/24
1827,Outside,2017-06-24 10:24:33.700,2017-06-24 10:25:52.750,3,outside-short,2487,79.05,24,0,06/24

In [28]:
flights_count = flights.copy()
flights_count['half_hour'] = flights_count['start'].apply(lambda x: x.hour + round(x.minute/30)/2)
flights_count['20minute']= flights_count['start'].apply(lambda x: x.hour + math.floor((x.minute/20) * 3)/3)
flights_count['10minute']= flights_count['start'].apply(lambda x: x.hour + math.floor((x.minute/10) * 6)/6)
flights_count['5minute'] = flights_count['start'].apply(lambda x: x.hour + math.floor((x.minute/20) * 12)/12)

## FREQUENCY (D1)

Without filling empty bins

In [29]:
from scipy.spatial.distance import pdist, squareform
from scipy.stats import wasserstein_distance

In [30]:
flights_nofill = flights.groupby(['tagID','date']).size().unstack()
x = flights_nofill.apply(lambda x: [x.dropna().mean(), x.dropna().std(), stats.variation(x.dropna()), stats.skew(x.dropna())] if len(x.dropna()) > 3 and  x.dropna().std() != 0 else pd.NA, axis=1)
x = x.dropna()

In [31]:
x

tagID
508     [2.0, 1.5491933384829668, 0.7071067811865476, ...
515     [1.75, 0.9574271077563381, 0.47380354147934284...
516     [1.125, 0.3535533905932738, 0.2939723678960656...
517     [5.142857142857143, 2.4784787961282104, 0.4461...
638     [3.3333333333333335, 0.816496580927726, 0.2236...
1237    [4.0, 2.0, 0.4629100498862757, 1.2151388809514...
1361    [2.7142857142857144, 1.7043362064926932, 0.581...
1407                  [6.0, 3.4641016151377544, 0.5, 0.0]
1607    [15.375, 9.28804915700047, 0.5650845160489477,...
1609    [4.142857142857143, 2.7945525240230875, 0.6245...
1621    [4.0, 2.3664319132398464, 0.5400617248673217, ...
1652    [1.5714285714285714, 0.7867957924694432, 0.463...
1698    [4.5, 3.7859388972001824, 0.7286042804780001, ...
1722    [2.1666666666666665, 1.1690451944500122, 0.492...
1780    [4.0, 4.96655480858378, 1.14953406710222, 1.85...
1797    [3.375, 2.38671920665766, 0.6615026333145093, ...
1900    [2.75, 2.8722813232690143, 0.9045340337332909,...
2487    [2.25, 0.9574271077563381, 0.3685138655950444,...
dtype: object

In [32]:
array = np.array(x.tolist())
squareform(pdist(array))

array([[ 0.        ,  1.14675545,  1.75910411,  3.71572018,  2.5906119 ,
         2.0742443 ,  1.19563282,  4.65937409, 15.53535671,  2.61485742,
         2.5876211 ,  1.06372699,  3.38556276,  1.03778608,  4.0081583 ,
         1.93942889,  1.5726816 ,  2.04114037],
       [ 1.14675545,  0.        ,  1.98397065,  3.80561249,  1.96026593,
         2.58273297,  1.22456957,  4.95883347, 15.98448695,  3.02189798,
         2.70103882,  0.44208457,  3.980371  ,  0.46773764,  4.84115054,
         2.17811592,  2.27596757,  1.11121101],
       [ 1.75910411,  1.98397065,  0.        ,  5.23098226,  3.67022877,
         3.48037629,  2.76441581,  6.21501728, 16.99884455,  4.24353448,
         4.18577616,  1.54852053,  5.00774629,  2.22681651,  5.51821312,
         3.61545756,  3.28661143,  3.04300827],
       [ 3.71572018,  3.80561249,  5.23098226,  0.        ,  2.48628096,
         1.97054112,  2.67304535,  1.34520684, 12.29225321,  1.39467446,
         1.19500192,  4.12340361,  1.95631187,  3.34991483,  3.56288447,
         1.89836346,  2.82908119,  3.27403963],
       [ 2.5906119 ,  1.96026593,  3.67022877,  2.48628096,  0.        ,
         2.30055382,  1.58587815,  3.81959641, 14.73374104,  2.48899006,
         1.82726235,  2.31752815,  3.59745227,  1.67271718,  4.96621941,
         1.89223424,  2.80948711,  1.10999295],
       [ 2.0742443 ,  2.58273297,  3.48037629,  1.97054112,  2.30055382,
         0.        ,  1.51664093,  2.76071217, 13.58188524,  1.03689125,
         1.27152948,  2.73788661,  1.89116991,  2.14052247,  3.1107673 ,
         1.16461251,  1.59394605,  2.6603408 ],
       [ 1.19563282,  1.22456957,  2.76441581,  2.67304535,  1.58587815,
         1.51664093,  0.        ,  3.75849565, 14.77293645,  1.80083324,
         1.52319302,  1.51951456,  2.78837108,  0.77099306,  3.80904834,
         0.96382082,  1.3480975 ,  1.32636901],
       [ 4.65937409,  4.95883347,  6.21501728,  1.34520684,  3.81959641,
         2.76071217,  3.75849565,  0.        , 11.03839684,  2.06271365,
         2.28177206,  5.24604209,  1.82283832,  4.49438599,  3.17920809,
         2.86162593,  3.49465975,  4.5394528 ],
       [15.53535671, 15.98448695, 16.99884455, 12.29225321, 14.73374104,
        13.58188524, 14.77293645, 11.03839684,  0.        , 12.99682489,
        13.31664429, 16.24515047, 12.24186438, 15.51874162, 12.35075201,
        13.85291737, 14.22055937, 15.54994329],
       [ 2.61485742,  3.02189798,  4.24353448,  1.39467446,  2.48899006,
         1.03689125,  1.80083324,  2.06271365, 12.99682489,  0.        ,
         0.7435296 ,  3.27794276,  1.12257023,  2.56407371,  2.57258187,
         0.90570154,  1.50199735,  2.86111559],
       [ 2.5876211 ,  2.70103882,  4.18577616,  1.19500192,  1.82726235,
         1.27152948,  1.52319302,  2.28177206, 13.31664429,  0.7435296 ,
         0.        ,  3.02299211,  1.79372483,  2.24384159,  3.24964607,
         0.7191846 ,  1.7571202 ,  2.30665325],
       [ 1.06372699,  0.44208457,  1.54852053,  4.12340361,  2.31752815,
         2.73788661,  1.51951456,  5.24604209, 16.24515047,  3.27794276,
         3.02299211,  0.        ,  4.20133095,  0.79993212,  4.98219159,
         2.47559185,  2.444424  ,  1.52642116],
       [ 3.38556276,  3.980371  ,  5.00774629,  1.95631187,  3.59745227,
         1.89116991,  2.78837108,  1.82283832, 12.24186438,  1.12257023,
         1.79372483,  4.20133095,  0.        ,  3.54530436,  1.61870593,
         1.90183327,  1.98493627,  3.91124608],
       [ 1.03778608,  0.46773764,  2.22681651,  3.34991483,  1.67271718,
         2.14052247,  0.77099306,  4.49438599, 15.51874162,  2.56407371,
         2.24384159,  0.79993212,  3.54530436,  0.        ,  4.48042104,
         1.73060115,  1.93534227,  1.01457982],
       [ 4.0081583 ,  4.84115054,  5.51821312,  3.56288447,  4.96621941,
         3.1107673 ,  3.80904834,  3.17920809, 12.35075201,  2.57258187,
         3.24964607,  4.98219159,  1.61870593,  4.48042104,  0.        ,
         3.09640405,  2.57402767,  5.02435424],
       [ 1.93942889,  2.17811592,  3.61545756,  1.89836346,  1.89223424,
         1.16461251,  0.96382082,  2.86162593, 13.85291737,  0.90570154,
         0.7191846 ,  2.47559185,  1.90183327,  1.73060115,  3.09640405,
         0.        ,  1.10519651,  2.01955991],
       [ 1.5726816 ,  2.27596757,  3.28661143,  2.82908119,  2.80948711,
         1.59394605,  1.3480975 ,  3.49465975, 14.22055937,  1.50199735,
         1.7571202 ,  2.444424  ,  1.98493627,  1.93534227,  2.57402767,
         1.10519651,  0.        ,  2.57594618],
       [ 2.04114037,  1.11121101,  3.04300827,  3.27403963,  1.10999295,
         2.6603408 ,  1.32636901,  4.5394528 , 15.54994329,  2.86111559,
         2.30665325,  1.52642116,  3.91124608,  1.01457982,  5.02435424,
         2.01955991,  2.57594618,  0.        ]])

In [33]:
x = flights_nofill.apply(lambda x: [v for v in x if pd.notna(v)],axis=1)
x

tagID
197                                        [3.0, 1.0]
508                    [1.0, 1.0, 2.0, 2.0, 5.0, 1.0]
515                              [3.0, 2.0, 1.0, 1.0]
516          [1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0]
517               [4.0, 8.0, 7.0, 2.0, 2.0, 7.0, 6.0]
638                    [4.0, 4.0, 4.0, 3.0, 2.0, 3.0]
661                                             [1.0]
677                                             [3.0]
1230                                [39.0, 2.0, 19.0]
1237              [3.0, 3.0, 5.0, 2.0, 3.0, 4.0, 8.0]
1361              [5.0, 1.0, 3.0, 1.0, 2.0, 2.0, 5.0]
1404                                            [3.0]
1407                             [9.0, 9.0, 3.0, 3.0]
1415                                       [1.0, 2.0]
1607    [24.0, 6.0, 23.0, 4.0, 5.0, 21.0, 14.0, 26.0]
1609              [2.0, 1.0, 9.0, 4.0, 6.0, 2.0, 5.0]
1621                   [6.0, 3.0, 5.0, 1.0, 7.0, 2.0]
1651                                            [2.0]
1652              [2.0, 1.0, 1.0, 1.0, 2.0, 1.0, 3.0]
1698                            [10.0, 2.0, 2.0, 4.0]
1722                   [1.0, 3.0, 2.0, 2.0, 1.0, 4.0]
1780             [1.0, 2.0, 2.0, 1.0, 15.0, 3.0, 4.0]
1786                                       [4.0, 3.0]
1797         [5.0, 3.0, 1.0, 1.0, 6.0, 3.0, 7.0, 1.0]
1900                             [1.0, 1.0, 2.0, 7.0]
1979                                            [1.0]
2258                                            [1.0]
2487                             [3.0, 3.0, 1.0, 2.0]
dtype: object

In [34]:
arrays = [wasserstein_distance(i,j) for i in x for j in x]
arr = np.array(arrays).reshape((len(x),len(x)))
arr

array([[ 0.        ,  0.66666667,  0.25      ,  0.875     ,  3.14285714,
         1.33333333,  1.        ,  1.        , 18.        ,  2.        ,
         0.85714286,  1.        ,  4.        ,  0.5       , 13.375     ,
         2.14285714,  2.        ,  1.        ,  0.42857143,  2.5       ,
         0.5       ,  2.14285714,  1.5       ,  1.375     ,  1.25      ,
         1.        ,  1.        ,  0.25      ],
       [ 0.66666667,  0.        ,  0.41666667,  0.875     ,  3.14285714,
         1.66666667,  1.        ,  1.66666667, 18.        ,  2.        ,
         0.71428571,  1.66666667,  4.        ,  0.5       , 13.375     ,
         2.14285714,  2.        ,  1.        ,  0.42857143,  2.5       ,
         0.5       ,  2.04761905,  1.83333333,  1.375     ,  0.75      ,
         1.        ,  1.        ,  0.91666667],
       [ 0.25      ,  0.41666667,  0.        ,  0.625     ,  3.39285714,
         1.58333333,  0.75      ,  1.25      , 18.25      ,  2.25      ,
         0.96428571,  1.25      ,  4.25      ,  0.25      , 13.625     ,
         2.39285714,  2.25      ,  0.75      ,  0.17857143,  2.75      ,
         0.41666667,  2.25      ,  1.75      ,  1.625     ,  1.        ,
         0.75      ,  0.75      ,  0.5       ],
       [ 0.875     ,  0.875     ,  0.625     ,  0.        ,  4.01785714,
         2.20833333,  0.125     ,  1.875     , 18.875     ,  2.875     ,
         1.58928571,  1.875     ,  4.875     ,  0.375     , 14.25      ,
         3.01785714,  2.875     ,  0.875     ,  0.44642857,  3.375     ,
         1.04166667,  2.875     ,  2.375     ,  2.25      ,  1.625     ,
         0.125     ,  0.125     ,  1.125     ],
       [ 3.14285714,  3.14285714,  3.39285714,  4.01785714,  0.        ,
         2.04761905,  4.14285714,  2.71428571, 15.04761905,  1.42857143,
         2.42857143,  2.71428571,  1.57142857,  3.64285714, 10.23214286,
         1.28571429,  1.14285714,  3.14285714,  3.57142857,  1.85714286,
         2.97619048,  3.14285714,  2.21428571,  1.76785714,  2.39285714,
         4.14285714,  4.14285714,  2.89285714],
       [ 1.33333333,  1.66666667,  1.58333333,  2.20833333,  2.04761905,
         0.        ,  2.33333333,  0.66666667, 17.        ,  0.80952381,
         1.19047619,  0.66666667,  2.66666667,  1.83333333, 12.04166667,
         1.61904762,  1.33333333,  1.33333333,  1.76190476,  1.83333333,
         1.16666667,  2.47619048,  0.16666667,  1.45833333,  2.08333333,
         2.33333333,  2.33333333,  1.08333333],
       [ 1.        ,  1.        ,  0.75      ,  0.125     ,  4.14285714,
         2.33333333,  0.        ,  2.        , 19.        ,  3.        ,
         1.71428571,  2.        ,  5.        ,  0.5       , 14.375     ,
         3.14285714,  3.        ,  1.        ,  0.57142857,  3.5       ,
         1.16666667,  3.        ,  2.5       ,  2.375     ,  1.75      ,
         0.        ,  0.        ,  1.25      ],
       [ 1.        ,  1.66666667,  1.25      ,  1.875     ,  2.71428571,
         0.66666667,  2.        ,  0.        , 17.66666667,  1.28571429,
         1.42857143,  0.        ,  3.        ,  1.5       , 12.375     ,
         2.28571429,  2.        ,  1.        ,  1.42857143,  2.5       ,
         1.16666667,  2.71428571,  0.5       ,  1.875     ,  2.25      ,
         2.        ,  2.        ,  0.75      ],
       [18.        , 18.        , 18.25      , 18.875     , 15.04761905,
        17.        , 19.        , 17.66666667,  0.        , 16.38095238,
        17.28571429, 17.66666667, 14.66666667, 18.5       ,  7.375     ,
        15.85714286, 16.        , 18.        , 18.42857143, 15.5       ,
        17.83333333, 16.        , 17.16666667, 16.625     , 17.25      ,
        19.        , 19.        , 17.75      ],
       [ 2.        ,  2.        ,  2.25      ,  2.875     ,  1.42857143,
         0.80952381,  3.        ,  1.28571429, 16.38095238,  0.        ,
         1.28571429,  1.28571429,  2.        ,  2.5       , 11.375     ,
         1.        ,  1.        ,  2.        ,  2.42857143,  1.28571429,
         1.83333333,  2.        ,  0.92857143,  1.01785714,  1.67857143,
         3.        ,  3.        ,  1.75      ],
       [ 0.85714286,  0.71428571,  0.96428571,  1.58928571,  2.42857143,
         1.19047619,  1.71428571,  1.42857143, 17.28571429,  1.28571429,
         0.        ,  1.42857143,  3.28571429,  1.21428571, 12.66071429,
         1.42857143,  1.28571429,  1.28571429,  1.14285714,  1.85714286,
         0.54761905,  1.57142857,  1.35714286,  0.83928571,  0.96428571,
         1.71428571,  1.71428571,  0.67857143],
       [ 1.        ,  1.66666667,  1.25      ,  1.875     ,  2.71428571,
         0.66666667,  2.        ,  0.        , 17.66666667,  1.28571429,
         1.42857143,  0.        ,  3.        ,  1.5       , 12.375     ,
         2.28571429,  2.        ,  1.        ,  1.42857143,  2.5       ,
         1.16666667,  2.71428571,  0.5       ,  1.875     ,  2.25      ,
         2.        ,  2.        ,  0.75      ],
       [ 4.        ,  4.        ,  4.25      ,  4.875     ,  1.57142857,
         2.66666667,  5.        ,  3.        , 14.66666667,  2.        ,
         3.28571429,  3.        ,  0.        ,  4.5       ,  9.375     ,
         2.        ,  2.        ,  4.        ,  4.42857143,  2.        ,
         3.83333333,  3.71428571,  2.5       ,  2.625     ,  3.25      ,
         5.        ,  5.        ,  3.75      ],
       [ 0.5       ,  0.5       ,  0.25      ,  0.375     ,  3.64285714,
         1.83333333,  0.5       ,  1.5       , 18.5       ,  2.5       ,
         1.21428571,  1.5       ,  4.5       ,  0.        , 13.875     ,
         2.64285714,  2.5       ,  0.5       ,  0.21428571,  3.        ,
         0.66666667,  2.5       ,  2.        ,  1.875     ,  1.25      ,
         0.5       ,  0.5       ,  0.75      ],
       [13.375     , 13.375     , 13.625     , 14.25      , 10.23214286,
        12.04166667, 14.375     , 12.375     ,  7.375     , 11.375     ,
        12.66071429, 12.375     ,  9.375     , 13.875     ,  0.        ,
        11.23214286, 11.375     , 13.375     , 13.80357143, 10.875     ,
        13.20833333, 11.375     , 11.875     , 12.        , 12.625     ,
        14.375     , 14.375     , 13.125     ],
       [ 2.14285714,  2.14285714,  2.39285714,  3.01785714,  1.28571429,
         1.61904762,  3.14285714,  2.28571429, 15.85714286,  1.        ,
         1.42857143,  2.28571429,  2.        ,  2.64285714, 11.23214286,
         0.        ,  0.61904762,  2.42857143,  2.57142857,  1.07142857,
         1.97619048,  1.85714286,  1.78571429,  0.875     ,  1.60714286,
         3.14285714,  3.14285714,  1.89285714],
       [ 2.        ,  2.        ,  2.25      ,  2.875     ,  1.14285714,
         1.33333333,  3.        ,  2.        , 16.        ,  1.        ,
         1.28571429,  2.        ,  2.        ,  2.5       , 11.375     ,
         0.61904762,  0.        ,  2.33333333,  2.42857143,  1.5       ,
         1.83333333,  2.28571429,  1.5       ,  0.625     ,  1.41666667,
         3.        ,  3.        ,  1.75      ],
       [ 1.        ,  1.        ,  0.75      ,  0.875     ,  3.14285714,
         1.33333333,  1.        ,  1.        , 18.        ,  2.        ,
         1.28571429,  1.        ,  4.        ,  0.5       , 13.375     ,
         2.42857143,  2.33333333,  0.        ,  0.71428571,  2.5       ,
         0.83333333,  2.57142857,  1.5       ,  2.125     ,  1.75      ,
         1.        ,  1.        ,  0.75      ],
       [ 0.42857143,  0.42857143,  0.17857143,  0.44642857,  3.57142857,
         1.76190476,  0.57142857,  1.42857143, 18.42857143,  2.42857143,
         1.14285714,  1.42857143,  4.42857143,  0.21428571, 13.80357143,
         2.57142857,  2.42857143,  0.71428571,  0.        ,  2.92857143,
         0.5952381 ,  2.42857143,  1.92857143,  1.80357143,  1.17857143,
         0.57142857,  0.57142857,  0.67857143],
       [ 2.5       ,  2.5       ,  2.75      ,  3.375     ,  1.85714286,
         1.83333333,  3.5       ,  2.5       , 15.5       ,  1.28571429,
         1.85714286,  2.5       ,  2.        ,  3.        , 10.875     ,
         1.07142857,  1.5       ,  2.5       ,  2.92857143,  0.        ,
         2.33333333,  1.92857143,  2.        ,  1.625     ,  1.75      ,
         3.5       ,  3.5       ,  2.25      ],
       [ 0.5       ,  0.5       ,  0.41666667,  1.04166667,  2.97619048,
         1.16666667,  1.16666667,  1.16666667, 17.83333333,  1.83333333,
         0.54761905,  1.16666667,  3.83333333,  0.66666667, 13.20833333,
         1.97619048,  1.83333333,  0.83333333,  0.5952381 ,  2.33333333,
         0.        ,  1.83333333,  1.33333333,  1.29166667,  1.08333333,
         1.16666667,  1.16666667,  0.41666667],
       [ 2.14285714,  2.04761905,  2.25      ,  2.875     ,  3.14285714,
         2.47619048,  3.        ,  2.71428571, 16.        ,  2.        ,
         1.57142857,  2.71428571,  3.71428571,  2.5       , 11.375     ,
         1.85714286,  2.28571429,  2.57142857,  2.42857143,  1.92857143,
         1.83333333,  0.        ,  2.64285714,  1.875     ,  1.89285714,
         3.        ,  3.        ,  1.96428571],
       [ 1.5       ,  1.83333333,  1.75      ,  2.375     ,  2.21428571,
         0.16666667,  2.5       ,  0.5       , 17.16666667,  0.92857143,
         1.35714286,  0.5       ,  2.5       ,  2.        , 11.875     ,
         1.78571429,  1.5       ,  1.5       ,  1.92857143,  2.        ,
         1.33333333,  2.64285714,  0.        ,  1.625     ,  2.25      ,
         2.5       ,  2.5       ,  1.25      ],
       [ 1.375     ,  1.375     ,  1.625     ,  2.25      ,  1.76785714,
         1.45833333,  2.375     ,  1.875     , 16.625     ,  1.01785714,
         0.83928571,  1.875     ,  2.625     ,  1.875     , 12.        ,
         0.875     ,  0.625     ,  2.125     ,  1.80357143,  1.625     ,
         1.29166667,  1.875     ,  1.625     ,  0.        ,  0.875     ,
         2.375     ,  2.375     ,  1.375     ],
       [ 1.25      ,  0.75      ,  1.        ,  1.625     ,  2.39285714,
         2.08333333,  1.75      ,  2.25      , 17.25      ,  1.67857143,
         0.96428571,  2.25      ,  3.25      ,  1.25      , 12.625     ,
         1.60714286,  1.41666667,  1.75      ,  1.17857143,  1.75      ,
         1.08333333,  1.89285714,  2.25      ,  0.875     ,  0.        ,
         1.75      ,  1.75      ,  1.5       ],
       [ 1.        ,  1.        ,  0.75      ,  0.125     ,  4.14285714,
         2.33333333,  0.        ,  2.        , 19.        ,  3.        ,
         1.71428571,  2.        ,  5.        ,  0.5       , 14.375     ,
         3.14285714,  3.        ,  1.        ,  0.57142857,  3.5       ,
         1.16666667,  3.        ,  2.5       ,  2.375     ,  1.75      ,
         0.        ,  0.        ,  1.25      ],
       [ 1.        ,  1.        ,  0.75      ,  0.125     ,  4.14285714,
         2.33333333,  0.        ,  2.        , 19.        ,  3.        ,
         1.71428571,  2.        ,  5.        ,  0.5       , 14.375     ,
         3.14285714,  3.        ,  1.        ,  0.57142857,  3.5       ,
         1.16666667,  3.        ,  2.5       ,  2.375     ,  1.75      ,
         0.        ,  0.        ,  1.25      ],
       [ 0.25      ,  0.91666667,  0.5       ,  1.125     ,  2.89285714,
         1.08333333,  1.25      ,  0.75      , 17.75      ,  1.75      ,
         0.67857143,  0.75      ,  3.75      ,  0.75      , 13.125     ,
         1.89285714,  1.75      ,  0.75      ,  0.67857143,  2.25      ,
         0.41666667,  1.96428571,  1.25      ,  1.375     ,  1.5       ,
         1.25      ,  1.25      ,  0.        ]])

Filling empty bins with 0

In [35]:
flights_freq = flights.groupby(['tagID','date']).size().unstack(fill_value=0)
flights_freq

date   06/21  06/22  06/23  06/24  06/25  06/26  06/27  06/28
tagID
197        3      0      0      1      0      0      0      0
508        1      0      0      1      2      2      5      1
515        3      2      1      0      0      0      1      0
516        1      1      2      1      1      1      1      1
517        4      8      7      2      2      7      6      0
638        4      4      4      3      0      2      3      0
661        0      1      0      0      0      0      0      0
677        3      0      0      0      0      0      0      0
1230      39      2     19      0      0      0      0      0
1237       3      3      5      2      3      4      8      0
1361       5      1      3      1      2      2      5      0
1404       3      0      0      0      0      0      0      0
1407       9      9      3      3      0      0      0      0
1415       1      2      0      0      0      0      0      0
1607      24      6     23      4      5     21     14     26
1609       2      1      9      4      6      2      5      0
1621       6      3      5      1      7      2      0      0
1651       2      0      0      0      0      0      0      0
1652       2      1      1      1      2      1      3      0
1698      10      2      2      4      0      0      0      0
1722       1      3      0      2      2      1      4      0
1780       1      2      2      1      0     15      3      4
1786       4      3      0      0      0      0      0      0
1797       5      3      1      1      6      3      7      1
1900       1      1      2      7      0      0      0      0
1979       1      0      0      0      0      0      0      0
2258       0      1      0      0      0      0      0      0
2487       3      3      1      2      0      0      0      0

In [36]:
x = flights_freq.apply(lambda x: [x.mean(), x.std(), stats.variation(x), stats.skew(x)], axis=1)
x

tagID
197                 [0.5, 1.0690449676496976, 2.0, 1.875]
508     [1.5, 1.6035674514745464, 1.0, 1.3333333333333...
515     [0.875, 1.1259916264596033, 1.203735681882337,...
516     [1.125, 0.3535533905932738, 0.2939723678960656...
517     [4.5, 2.9277002188455996, 0.6085806194501846, ...
638     [2.5, 1.6903085094570331, 0.6324555320336759, ...
661     [0.125, 0.3535533905932738, 2.6457513110645907...
677     [0.375, 1.0606601717798212, 2.6457513110645907...
1230    [7.5, 14.322808982279179, 1.786368134263235, 1...
1237    [3.5, 2.32992949004287, 0.6226998490772392, 0....
1361    [2.375, 1.8468119248354136, 0.7273828926886976...
1404    [0.375, 1.0606601717798212, 2.6457513110645907...
1407    [3.0, 3.927922024247863, 1.2247448713915892, 0...
1415    [0.375, 0.7440238091428449, 1.8559214542766738...
1607    [15.375, 9.28804915700047, 0.5650845160489477,...
1609    [3.625, 2.9730936268953445, 0.7671929469409307...
1621    [3.0, 2.7255405754769875, 0.8498365855987974, ...
1651    [0.25, 0.7071067811865476, 2.6457513110645907,...
1652    [1.375, 0.9161253813129043, 0.6232413273091858...
1698    [2.25, 3.453776401067595, 1.435871998146676, 1...
1722    [1.625, 1.407885953173359, 0.8104349040655953,...
1780    [3.5, 4.810702354423639, 1.2857142857142858, 1...
1786    [0.875, 1.6420805617960927, 1.755457961063501,...
1797    [3.375, 2.38671920665766, 0.6615026333145093, ...
1900    [1.375, 2.38671920665766, 1.6236882817719773, ...
1979    [0.125, 0.3535533905932738, 2.6457513110645907...
2258    [0.125, 0.3535533905932738, 2.6457513110645907...
2487    [1.125, 1.3562026818605375, 1.1276546183435798...
dtype: object

In [37]:
array = np.array(x.tolist())
squareform(pdist(array))

array([[ 0.        ,  1.60596297,  1.32023758,  1.99182454,  5.09982863,
         3.56413593,  1.10626826,  0.76614069, 14.99305811,  3.76362954,
         2.79808605,  0.76614069,  4.01803783,  0.48842014, 17.17865664,
         4.0779756 ,  3.58997495,  0.87451444,  2.2105665 ,  3.0260306 ,
         2.23969147,  4.84976968,  0.96217355,  3.76412973,  1.62590944,
         1.10626826,  1.10626826,  1.76817803],
       [ 1.60596297,  0.        ,  0.92437193,  1.75352175,  3.67282061,
         2.26545055,  2.65233122,  2.26761417, 14.08761855,  2.28869099,
         1.30990426,  2.26761417,  2.82316395,  1.67044586, 15.93897929,
         2.65282685,  2.15841755,  2.43881989,  1.2320962 ,  2.05786951,
         0.99477558,  3.84440883,  0.98521029,  2.28965945,  1.14941161,
         2.65233122,  2.65233122,  0.95583461],
       [ 1.32023758,  0.92437193,  0.        ,  1.83793002,  4.25459813,
         2.38928164,  2.26488996,  2.05544008, 14.79412035,  2.96237635,
         1.79188673,  2.05544008,  3.51748079,  1.12802526, 16.68625038,
         3.35751551,  2.75411096,  2.12994254,  0.93945258,  2.79833015,
         1.02689361,  4.65260257,  0.83360035,  2.90614317,  1.73165676,
         2.26488996,  2.26488996,  0.52527825],
       [ 1.99182454,  1.75352175,  1.83793002,  0.        ,  4.95739956,
         3.51965103,  2.55555556,  2.5677547 , 15.44259307,  3.5362131 ,
         2.71276634,  2.5677547 ,  4.38911346,  1.91037689, 16.99884455,
         4.02979405,  3.66550311,  2.53406574,  2.00239239,  3.55794779,
         2.27464581,  5.15518161,  2.21471646,  3.61545756,  2.47218886,
         2.55555556,  2.55555556,  2.197194  ],
       [ 5.09982863,  3.67282061,  4.25459813,  4.95739956,  0.        ,
         2.38410939,  6.03132626,  5.57776865, 11.98717583,  1.44425946,
         2.48855671,  5.57776865,  2.19521805,  5.16902112, 12.59881215,
         1.22255781,  1.62681942,  5.79685905,  3.775496  ,  3.07360413,
         3.32415885,  3.17221884,  4.29132982,  1.38937902,  3.96799628,
         6.03132626,  6.03132626,  3.83764773],
       [ 3.56413593,  2.26545055,  2.38928164,  3.51965103,  2.38410939,
         0.        ,  4.48070668,  4.19061752, 13.81924554,  1.71926952,
         1.11591174,  4.19061752,  2.7928163 ,  3.44581447, 14.95756034,
         2.10646368,  1.49811605,  4.321849  ,  1.72578937,  2.97278137,
         1.40612831,  4.25793004,  2.74743806,  1.49909181,  3.0373904 ,
         4.48070668,  4.48070668,  1.89764722],
       [ 1.10626826,  2.65233122,  2.26488996,  2.55555556,  6.03132626,
         4.48070668,  0.        ,  0.75      , 15.83461319,  4.71587516,
         3.78832336,  0.75      ,  5.01669601,  1.15485329, 17.96430874,
         5.05413532,  4.5937172 ,  0.375     ,  3.0808609 ,  4.00859897,
         3.20556802,  5.76125386,  2.01535384,  4.73008432,  2.62453542,
         0.        ,  0.        ,  2.72713273],
       [ 0.76614069,  2.26761417,  2.05544008,  2.5677547 ,  5.57776865,
         4.19061752,  0.75      ,  0.        , 15.09484893,  4.28012391,
         3.41717829,  0.        ,  4.38603674,  1.10407316, 17.40742954,
         4.54446857,  4.10764425,  0.375     ,  2.93830001,  3.34432179,
         2.93208371,  5.07579408,  1.5578506 ,  4.29370085,  1.98755012,
         0.75      ,  0.75      ,  2.46612909],
       [14.99305811, 14.08761855, 14.79412035, 15.44259307, 11.98717583,
        13.81924554, 15.83461319, 15.09484893,  0.        , 12.73557533,
        13.57841513, 15.09484893, 11.36706839, 15.33474202,  9.59052184,
        12.07947876, 12.54391605, 15.46460781, 14.83354457, 12.07564895,
        14.27251423, 10.33841807, 14.31112651, 12.74038897, 13.42019009,
        15.83461319, 15.83461319, 14.50471638],
       [ 3.76362954,  2.28869099,  2.96237635,  3.5362131 ,  1.44425946,
         1.71926952,  4.71587516,  4.28012391, 12.73557533,  0.        ,
         1.23793355,  4.28012391,  1.79504023,  3.84333786, 13.78454804,
         0.67112582,  0.74362789,  4.4876324 ,  2.55929923,  2.11669279,
         2.1068873 ,  2.92265121,  3.01489692,  0.28416095,  2.68743149,
         4.71587516,  4.71587516,  2.61728538],
       [ 2.79808605,  1.30990426,  1.79188673,  2.71276634,  2.48855671,
         1.11591174,  3.78832336,  3.41717829, 13.57841513,  1.23793355,
         0.        ,  3.41717829,  2.26245511,  2.78878064, 14.99239531,
         1.68837963,  1.09670634,  3.58798351,  1.37058729,  2.10119322,
         0.8741059 ,  3.57088568,  2.00340359,  1.14237116,  2.05184769,
         3.78832336,  3.78832336,  1.40295462],
       [ 0.76614069,  2.26761417,  2.05544008,  2.5677547 ,  5.57776865,
         4.19061752,  0.75      ,  0.        , 15.09484893,  4.28012391,
         3.41717829,  0.        ,  4.38603674,  1.10407316, 17.40742954,
         4.54446857,  4.10764425,  0.375     ,  2.93830001,  3.34432179,
         2.93208371,  5.07579408,  1.5578506 ,  4.29370085,  1.98755012,
         0.75      ,  0.75      ,  2.46612909],
       [ 4.01803783,  2.82316395,  3.51748079,  4.38911346,  2.19521805,
         2.7928163 ,  5.01669601,  4.38603674, 11.36706839,  1.79504023,
         2.26245511,  4.38603674,  0.        ,  4.2409236 , 13.53894154,
         1.25518647,  1.37231525,  4.69698345,  3.50062307,  1.18714123,
         2.93244384,  1.54138372,  3.19466927,  1.75103987,  2.51288701,
         5.01669601,  5.01669601,  3.19990107],
       [ 0.48842014,  1.67044586,  1.12802526,  1.91037689,  5.16902112,
         3.44581447,  1.15485329,  1.10407316, 15.33474202,  3.84333786,
         2.78878064,  1.10407316,  4.2409236 ,  0.        , 17.39870149,
         4.20920874,  3.67429801,  1.06569547,  1.98132854,  3.32189274,
         2.11837202,  5.17663599,  1.08101608,  3.82611461,  1.96330614,
         1.15485329,  1.15485329,  1.61299087],
       [17.17865664, 15.93897929, 16.68625038, 16.99884455, 12.59881215,
        14.95756034, 17.96430874, 17.40742954,  9.59052184, 13.78454804,
        14.99239531, 17.40742954, 13.53894154, 17.39870149,  0.        ,
        13.36180179, 14.01761638, 17.68408524, 16.32238984, 14.49665872,
        15.86002748, 12.89316969, 16.49735821, 13.85291737, 15.78022839,
        17.96430874, 17.96430874, 16.33269367],
       [ 4.0779756 ,  2.65282685,  3.35751551,  4.02979405,  1.22255781,
         2.10646368,  5.05413532,  4.54446857, 12.07947876,  0.67112582,
         1.68837963,  4.54446857,  1.25518647,  4.20920874, 13.36180179,
         0.        ,  0.7376956 ,  4.79141046,  3.05683038,  1.89577604,
         2.54633373,  2.37769565,  3.2824692 ,  0.6858768 ,  2.80759414,
         5.05413532,  5.05413532,  2.99973851],
       [ 3.58997495,  2.15841755,  2.75411096,  3.66550311,  1.62681942,
         1.49811605,  4.5937172 ,  4.10764425, 12.54391605,  0.74362789,
         1.09670634,  4.10764425,  1.37231525,  3.67429801, 14.01761638,
         0.7376956 ,  0.        ,  4.34129756,  2.44545155,  1.7716788 ,
         1.90819716,  2.7732108 ,  2.73077778,  0.54293083,  2.44012429,
         4.5937172 ,  4.5937172 ,  2.3494242 ],
       [ 0.87451444,  2.43881989,  2.12994254,  2.53406574,  5.79685905,
         4.321849  ,  0.375     ,  0.375     , 15.46460781,  4.4876324 ,
         3.58798351,  0.375     ,  4.69698345,  1.06569547, 17.68408524,
         4.79141046,  4.34129756,  0.        ,  2.9869768 ,  3.67233604,
         3.0488958 ,  5.41638633,  1.76171785,  4.50157277,  2.29753038,
         0.375     ,  0.375     ,  2.57272187],
       [ 2.2105665 ,  1.2320962 ,  0.93945258,  2.00239239,  3.775496  ,
         1.72578937,  3.0808609 ,  2.93830001, 14.83354457,  2.55929923,
         1.37058729,  2.93830001,  3.50062307,  1.98132854, 16.32238984,
         3.05683038,  2.44545155,  2.9869768 ,  0.        ,  3.04477921,
         0.58258814,  4.7573233 ,  1.66974776,  2.48342172,  2.32215286,
         3.0808609 ,  3.0808609 ,  0.72272661],
       [ 3.0260306 ,  2.05786951,  2.79833015,  3.55794779,  3.07360413,
         2.97278137,  4.00859897,  3.34432179, 12.07564895,  2.11669279,
         2.10119322,  3.34432179,  1.18714123,  3.32189274, 14.49665872,
         1.89577604,  1.7716788 ,  3.67233604,  3.04477921,  0.        ,
         2.52731688,  1.89352667,  2.320529  ,  2.13255816,  1.42622922,
         4.00859897,  4.00859897,  2.63066494],
       [ 2.23969147,  0.99477558,  1.02689361,  2.27464581,  3.32415885,
         1.40612831,  3.20556802,  2.93208371, 14.27251423,  2.1068873 ,
         0.8741059 ,  2.93208371,  2.93244384,  2.11837202, 15.86002748,
         2.54633373,  1.90819716,  3.0488958 ,  0.58258814,  2.52731688,
         0.        ,  4.22497485,  1.50008601,  2.01131617,  1.98230813,
         3.20556802,  3.20556802,  0.60533063],
       [ 4.84976968,  3.84440883,  4.65260257,  5.15518161,  3.17221884,
         4.25793004,  5.76125386,  5.07579408, 10.33841807,  2.92265121,
         3.57088568,  5.07579408,  1.54138372,  5.17663599, 12.89316969,
         2.37769565,  2.7732108 ,  5.41638633,  4.7573233 ,  1.89352667,
         4.22497485,  0.        ,  4.20534117,  2.9958995 ,  3.24251249,
         5.76125386,  5.76125386,  4.44720105],
       [ 0.96217355,  0.98521029,  0.83360035,  2.21471646,  4.29132982,
         2.74743806,  2.01535384,  1.5578506 , 14.31112651,  3.01489692,
         2.00340359,  1.5578506 ,  3.19466927,  1.08101608, 16.49735821,
         3.2824692 ,  2.73077778,  1.76171785,  1.66974776,  2.320529  ,
         1.50008601,  4.20534117,  0.        ,  2.9717567 ,  1.10915504,
         2.01535384,  2.01535384,  1.04606081],
       [ 3.76412973,  2.28965945,  2.90614317,  3.61545756,  1.38937902,
         1.49909181,  4.73008432,  4.29370085, 12.74038897,  0.28416095,
         1.14237116,  4.29370085,  1.75103987,  3.82611461, 13.85291737,
         0.6858768 ,  0.54293083,  4.50157277,  2.48342172,  2.13255816,
         2.01131617,  2.9958995 ,  2.9717567 ,  0.        ,  2.70716801,
         4.73008432,  4.73008432,  2.52372002],
       [ 1.62590944,  1.14941161,  1.73165676,  2.47218886,  3.96799628,
         3.0373904 ,  2.62453542,  1.98755012, 13.42019009,  2.68743149,
         2.05184769,  1.98755012,  2.51288701,  1.96330614, 15.78022839,
         2.80759414,  2.44012429,  2.29753038,  2.32215286,  1.42622922,
         1.98230813,  3.24251249,  1.10915504,  2.70716801,  0.        ,
         2.62453542,  2.62453542,  1.8131946 ],
       [ 1.10626826,  2.65233122,  2.26488996,  2.55555556,  6.03132626,
         4.48070668,  0.        ,  0.75      , 15.83461319,  4.71587516,
         3.78832336,  0.75      ,  5.01669601,  1.15485329, 17.96430874,
         5.05413532,  4.5937172 ,  0.375     ,  3.0808609 ,  4.00859897,
         3.20556802,  5.76125386,  2.01535384,  4.73008432,  2.62453542,
         0.        ,  0.        ,  2.72713273],
       [ 1.10626826,  2.65233122,  2.26488996,  2.55555556,  6.03132626,
         4.48070668,  0.        ,  0.75      , 15.83461319,  4.71587516,
         3.78832336,  0.75      ,  5.01669601,  1.15485329, 17.96430874,
         5.05413532,  4.5937172 ,  0.375     ,  3.0808609 ,  4.00859897,
         3.20556802,  5.76125386,  2.01535384,  4.73008432,  2.62453542,
         0.        ,  0.        ,  2.72713273],
       [ 1.76817803,  0.95583461,  0.52527825,  2.197194  ,  3.83764773,
         1.89764722,  2.72713273,  2.46612909, 14.50471638,  2.61728538,
         1.40295462,  2.46612909,  3.19990107,  1.61299087, 16.33269367,
         2.99973851,  2.3494242 ,  2.57272187,  0.72272661,  2.63066494,
         0.60533063,  4.44720105,  1.04606081,  2.52372002,  1.8131946 ,
         2.72713273,  2.72713273,  0.        ]])

In [38]:
x = flights_freq.apply(lambda x: x.tolist(), axis=1)
x

tagID
197          [3, 0, 0, 1, 0, 0, 0, 0]
508          [1, 0, 0, 1, 2, 2, 5, 1]
515          [3, 2, 1, 0, 0, 0, 1, 0]
516          [1, 1, 2, 1, 1, 1, 1, 1]
517          [4, 8, 7, 2, 2, 7, 6, 0]
638          [4, 4, 4, 3, 0, 2, 3, 0]
661          [0, 1, 0, 0, 0, 0, 0, 0]
677          [3, 0, 0, 0, 0, 0, 0, 0]
1230       [39, 2, 19, 0, 0, 0, 0, 0]
1237         [3, 3, 5, 2, 3, 4, 8, 0]
1361         [5, 1, 3, 1, 2, 2, 5, 0]
1404         [3, 0, 0, 0, 0, 0, 0, 0]
1407         [9, 9, 3, 3, 0, 0, 0, 0]
1415         [1, 2, 0, 0, 0, 0, 0, 0]
1607    [24, 6, 23, 4, 5, 21, 14, 26]
1609         [2, 1, 9, 4, 6, 2, 5, 0]
1621         [6, 3, 5, 1, 7, 2, 0, 0]
1651         [2, 0, 0, 0, 0, 0, 0, 0]
1652         [2, 1, 1, 1, 2, 1, 3, 0]
1698        [10, 2, 2, 4, 0, 0, 0, 0]
1722         [1, 3, 0, 2, 2, 1, 4, 0]
1780        [1, 2, 2, 1, 0, 15, 3, 4]
1786         [4, 3, 0, 0, 0, 0, 0, 0]
1797         [5, 3, 1, 1, 6, 3, 7, 1]
1900         [1, 1, 2, 7, 0, 0, 0, 0]
1979         [1, 0, 0, 0, 0, 0, 0, 0]
2258         [0, 1, 0, 0, 0, 0, 0, 0]
2487         [3, 3, 1, 2, 0, 0, 0, 0]
dtype: object

Full matrix

In [39]:
arrays = [wasserstein_distance(i,j) for i in x for j in x]
arr = np.array(arrays).reshape((len(x),len(x)))

In [40]:
arr

array([[ 0.   ,  1.   ,  0.375,  0.875,  4.   ,  2.   ,  0.375,  0.125,
         7.   ,  3.   ,  1.875,  0.125,  2.5  ,  0.125, 14.875,  3.125,
         2.5  ,  0.25 ,  0.875,  1.75 ,  1.125,  3.   ,  0.375,  2.875,
         0.875,  0.375,  0.375,  0.625],
       [ 1.   ,  0.   ,  0.625,  0.875,  3.   ,  1.25 ,  1.375,  1.125,
         6.75 ,  2.   ,  0.875,  1.125,  2.   ,  1.125, 13.875,  2.125,
         1.5  ,  1.25 ,  0.375,  1.25 ,  0.375,  2.   ,  0.875,  1.875,
         0.625,  1.375,  1.375,  0.625],
       [ 0.375,  0.625,  0.   ,  0.75 ,  3.625,  1.625,  0.75 ,  0.5  ,
         6.875,  2.625,  1.5  ,  0.5  ,  2.125,  0.5  , 14.5  ,  2.75 ,
         2.125,  0.625,  0.5  ,  1.375,  0.75 ,  2.625,  0.5  ,  2.5  ,
         0.5  ,  0.75 ,  0.75 ,  0.25 ],
       [ 0.875,  0.875,  0.75 ,  0.   ,  3.625,  1.875,  1.   ,  1.   ,
         7.625,  2.625,  1.5  ,  1.   ,  2.875,  0.75 , 14.25 ,  2.75 ,
         2.375,  0.875,  0.5  ,  2.125,  1.   ,  2.625,  1.25 ,  2.25 ,
         1.25 ,  1.   ,  1.   ,  1.   ],
       [ 4.   ,  3.   ,  3.625,  3.625,  0.   ,  2.   ,  4.375,  4.125,
         7.75 ,  1.25 ,  2.125,  4.125,  2.25 ,  4.125, 10.875,  1.125,
         1.5  ,  4.25 ,  3.125,  2.75 ,  2.875,  2.75 ,  3.625,  1.375,
         3.125,  4.375,  4.375,  3.375],
       [ 2.   ,  1.25 ,  1.625,  1.875,  2.   ,  0.   ,  2.375,  2.125,
         7.5  ,  1.   ,  0.875,  2.125,  2.   ,  2.125, 12.875,  1.375,
         1.   ,  2.25 ,  1.375,  1.75 ,  0.875,  2.   ,  1.625,  1.125,
         1.875,  2.375,  2.375,  1.375],
       [ 0.375,  1.375,  0.75 ,  1.   ,  4.375,  2.375,  0.   ,  0.25 ,
         7.375,  3.375,  2.25 ,  0.25 ,  2.875,  0.25 , 15.25 ,  3.5  ,
         2.875,  0.125,  1.25 ,  2.125,  1.5  ,  3.375,  0.75 ,  3.25 ,
         1.25 ,  0.   ,  0.   ,  1.   ],
       [ 0.125,  1.125,  0.5  ,  1.   ,  4.125,  2.125,  0.25 ,  0.   ,
         7.125,  3.125,  2.   ,  0.   ,  2.625,  0.25 , 15.   ,  3.25 ,
         2.625,  0.125,  1.   ,  1.875,  1.25 ,  3.125,  0.5  ,  3.   ,
         1.   ,  0.25 ,  0.25 ,  0.75 ],
       [ 7.   ,  6.75 ,  6.875,  7.625,  7.75 ,  7.5  ,  7.375,  7.125,
         0.   ,  7.25 ,  6.875,  7.125,  5.5  ,  7.125, 11.125,  6.875,
         6.75 ,  7.25 ,  7.125,  5.75 ,  6.875,  5.75 ,  6.625,  7.125,
         6.375,  7.375,  7.375,  6.625],
       [ 3.   ,  2.   ,  2.625,  2.625,  1.25 ,  1.   ,  3.375,  3.125,
         7.25 ,  0.   ,  1.125,  3.125,  1.75 ,  3.125, 11.875,  0.875,
         1.   ,  3.25 ,  2.125,  1.75 ,  1.875,  1.75 ,  2.625,  0.875,
         2.125,  3.375,  3.375,  2.375],
       [ 1.875,  0.875,  1.5  ,  1.5  ,  2.125,  0.875,  2.25 ,  2.   ,
         6.875,  1.125,  0.   ,  2.   ,  1.625,  2.   , 13.   ,  1.25 ,
         0.875,  2.125,  1.   ,  1.375,  0.75 ,  1.375,  1.5  ,  1.   ,
         1.5  ,  2.25 ,  2.25 ,  1.25 ],
       [ 0.125,  1.125,  0.5  ,  1.   ,  4.125,  2.125,  0.25 ,  0.   ,
         7.125,  3.125,  2.   ,  0.   ,  2.625,  0.25 , 15.   ,  3.25 ,
         2.625,  0.125,  1.   ,  1.875,  1.25 ,  3.125,  0.5  ,  3.   ,
         1.   ,  0.25 ,  0.25 ,  0.75 ],
       [ 2.5  ,  2.   ,  2.125,  2.875,  2.25 ,  2.   ,  2.875,  2.625,
         5.5  ,  1.75 ,  1.625,  2.625,  0.   ,  2.625, 12.375,  1.375,
         1.25 ,  2.75 ,  2.375,  1.   ,  1.875,  2.   ,  2.125,  1.625,
         1.625,  2.875,  2.875,  1.875],
       [ 0.125,  1.125,  0.5  ,  0.75 ,  4.125,  2.125,  0.25 ,  0.25 ,
         7.125,  3.125,  2.   ,  0.25 ,  2.625,  0.   , 15.   ,  3.25 ,
         2.625,  0.125,  1.   ,  1.875,  1.25 ,  3.125,  0.5  ,  3.   ,
         1.   ,  0.25 ,  0.25 ,  0.75 ],
       [14.875, 13.875, 14.5  , 14.25 , 10.875, 12.875, 15.25 , 15.   ,
        11.125, 11.875, 13.   , 15.   , 12.375, 15.   ,  0.   , 11.75 ,
        12.375, 15.125, 14.   , 13.125, 13.75 , 11.875, 14.5  , 12.   ,
        14.   , 15.25 , 15.25 , 14.25 ],
       [ 3.125,  2.125,  2.75 ,  2.75 ,  1.125,  1.375,  3.5  ,  3.25 ,
         6.875,  0.875,  1.25 ,  3.25 ,  1.375,  3.25 , 11.75 ,  0.   ,
         0.625,  3.375,  2.25 ,  1.625,  2.   ,  1.625,  2.75 ,  0.75 ,
         2.25 ,  3.5  ,  3.5  ,  2.5  ],
       [ 2.5  ,  1.5  ,  2.125,  2.375,  1.5  ,  1.   ,  2.875,  2.625,
         6.75 ,  1.   ,  0.875,  2.625,  1.25 ,  2.625, 12.375,  0.625,
         0.   ,  2.75 ,  1.875,  1.5  ,  1.375,  1.75 ,  2.125,  0.375,
         1.625,  2.875,  2.875,  1.875],
       [ 0.25 ,  1.25 ,  0.625,  0.875,  4.25 ,  2.25 ,  0.125,  0.125,
         7.25 ,  3.25 ,  2.125,  0.125,  2.75 ,  0.125, 15.125,  3.375,
         2.75 ,  0.   ,  1.125,  2.   ,  1.375,  3.25 ,  0.625,  3.125,
         1.125,  0.125,  0.125,  0.875],
       [ 0.875,  0.375,  0.5  ,  0.5  ,  3.125,  1.375,  1.25 ,  1.   ,
         7.125,  2.125,  1.   ,  1.   ,  2.375,  1.   , 14.   ,  2.25 ,
         1.875,  1.125,  0.   ,  1.625,  0.5  ,  2.125,  1.   ,  2.   ,
         1.   ,  1.25 ,  1.25 ,  0.5  ],
       [ 1.75 ,  1.25 ,  1.375,  2.125,  2.75 ,  1.75 ,  2.125,  1.875,
         5.75 ,  1.75 ,  1.375,  1.875,  1.   ,  1.875, 13.125,  1.625,
         1.5  ,  2.   ,  1.625,  0.   ,  1.125,  1.25 ,  1.375,  1.875,
         0.875,  2.125,  2.125,  1.125],
       [ 1.125,  0.375,  0.75 ,  1.   ,  2.875,  0.875,  1.5  ,  1.25 ,
         6.875,  1.875,  0.75 ,  1.25 ,  1.875,  1.25 , 13.75 ,  2.   ,
         1.375,  1.375,  0.5  ,  1.125,  0.   ,  1.875,  0.75 ,  1.75 ,
         1.   ,  1.5  ,  1.5  ,  0.5  ],
       [ 3.   ,  2.   ,  2.625,  2.625,  2.75 ,  2.   ,  3.375,  3.125,
         5.75 ,  1.75 ,  1.375,  3.125,  2.   ,  3.125, 11.875,  1.625,
         1.75 ,  3.25 ,  2.125,  1.25 ,  1.875,  0.   ,  2.625,  1.875,
         2.125,  3.375,  3.375,  2.375],
       [ 0.375,  0.875,  0.5  ,  1.25 ,  3.625,  1.625,  0.75 ,  0.5  ,
         6.625,  2.625,  1.5  ,  0.5  ,  2.125,  0.5  , 14.5  ,  2.75 ,
         2.125,  0.625,  1.   ,  1.375,  0.75 ,  2.625,  0.   ,  2.5  ,
         0.75 ,  0.75 ,  0.75 ,  0.5  ],
       [ 2.875,  1.875,  2.5  ,  2.25 ,  1.375,  1.125,  3.25 ,  3.   ,
         7.125,  0.875,  1.   ,  3.   ,  1.625,  3.   , 12.   ,  0.75 ,
         0.375,  3.125,  2.   ,  1.875,  1.75 ,  1.875,  2.5  ,  0.   ,
         2.   ,  3.25 ,  3.25 ,  2.25 ],
       [ 0.875,  0.625,  0.5  ,  1.25 ,  3.125,  1.875,  1.25 ,  1.   ,
         6.375,  2.125,  1.5  ,  1.   ,  1.625,  1.   , 14.   ,  2.25 ,
         1.625,  1.125,  1.   ,  0.875,  1.   ,  2.125,  0.75 ,  2.   ,
         0.   ,  1.25 ,  1.25 ,  0.75 ],
       [ 0.375,  1.375,  0.75 ,  1.   ,  4.375,  2.375,  0.   ,  0.25 ,
         7.375,  3.375,  2.25 ,  0.25 ,  2.875,  0.25 , 15.25 ,  3.5  ,
         2.875,  0.125,  1.25 ,  2.125,  1.5  ,  3.375,  0.75 ,  3.25 ,
         1.25 ,  0.   ,  0.   ,  1.   ],
       [ 0.375,  1.375,  0.75 ,  1.   ,  4.375,  2.375,  0.   ,  0.25 ,
         7.375,  3.375,  2.25 ,  0.25 ,  2.875,  0.25 , 15.25 ,  3.5  ,
         2.875,  0.125,  1.25 ,  2.125,  1.5  ,  3.375,  0.75 ,  3.25 ,
         1.25 ,  0.   ,  0.   ,  1.   ],
       [ 0.625,  0.625,  0.25 ,  1.   ,  3.375,  1.375,  1.   ,  0.75 ,
         6.625,  2.375,  1.25 ,  0.75 ,  1.875,  0.75 , 14.25 ,  2.5  ,
         1.875,  0.875,  0.5  ,  1.125,  0.5  ,  2.375,  0.5  ,  2.25 ,
         0.75 ,  1.   ,  1.   ,  0.   ]])

In [41]:
squareform(arr)

array([ 1.   ,  0.375,  0.875,  4.   ,  2.   ,  0.375,  0.125,  7.   ,
        3.   ,  1.875,  0.125,  2.5  ,  0.125, 14.875,  3.125,  2.5  ,
        0.25 ,  0.875,  1.75 ,  1.125,  3.   ,  0.375,  2.875,  0.875,
        0.375,  0.375,  0.625,  0.625,  0.875,  3.   ,  1.25 ,  1.375,
        1.125,  6.75 ,  2.   ,  0.875,  1.125,  2.   ,  1.125, 13.875,
        2.125,  1.5  ,  1.25 ,  0.375,  1.25 ,  0.375,  2.   ,  0.875,
        1.875,  0.625,  1.375,  1.375,  0.625,  0.75 ,  3.625,  1.625,
        0.75 ,  0.5  ,  6.875,  2.625,  1.5  ,  0.5  ,  2.125,  0.5  ,
       14.5  ,  2.75 ,  2.125,  0.625,  0.5  ,  1.375,  0.75 ,  2.625,
        0.5  ,  2.5  ,  0.5  ,  0.75 ,  0.75 ,  0.25 ,  3.625,  1.875,
        1.   ,  1.   ,  7.625,  2.625,  1.5  ,  1.   ,  2.875,  0.75 ,
       14.25 ,  2.75 ,  2.375,  0.875,  0.5  ,  2.125,  1.   ,  2.625,
        1.25 ,  2.25 ,  1.25 ,  1.   ,  1.   ,  1.   ,  2.   ,  4.375,
        4.125,  7.75 ,  1.25 ,  2.125,  4.125,  2.25 ,  4.125, 10.875,
        1.125,  1.5  ,  4.25 ,  3.125,  2.75 ,  2.875,  2.75 ,  3.625,
        1.375,  3.125,  4.375,  4.375,  3.375,  2.375,  2.125,  7.5  ,
        1.   ,  0.875,  2.125,  2.   ,  2.125, 12.875,  1.375,  1.   ,
        2.25 ,  1.375,  1.75 ,  0.875,  2.   ,  1.625,  1.125,  1.875,
        2.375,  2.375,  1.375,  0.25 ,  7.375,  3.375,  2.25 ,  0.25 ,
        2.875,  0.25 , 15.25 ,  3.5  ,  2.875,  0.125,  1.25 ,  2.125,
        1.5  ,  3.375,  0.75 ,  3.25 ,  1.25 ,  0.   ,  0.   ,  1.   ,
        7.125,  3.125,  2.   ,  0.   ,  2.625,  0.25 , 15.   ,  3.25 ,
        2.625,  0.125,  1.   ,  1.875,  1.25 ,  3.125,  0.5  ,  3.   ,
        1.   ,  0.25 ,  0.25 ,  0.75 ,  7.25 ,  6.875,  7.125,  5.5  ,
        7.125, 11.125,  6.875,  6.75 ,  7.25 ,  7.125,  5.75 ,  6.875,
        5.75 ,  6.625,  7.125,  6.375,  7.375,  7.375,  6.625,  1.125,
        3.125,  1.75 ,  3.125, 11.875,  0.875,  1.   ,  3.25 ,  2.125,
        1.75 ,  1.875,  1.75 ,  2.625,  0.875,  2.125,  3.375,  3.375,
        2.375,  2.   ,  1.625,  2.   , 13.   ,  1.25 ,  0.875,  2.125,
        1.   ,  1.375,  0.75 ,  1.375,  1.5  ,  1.   ,  1.5  ,  2.25 ,
        2.25 ,  1.25 ,  2.625,  0.25 , 15.   ,  3.25 ,  2.625,  0.125,
        1.   ,  1.875,  1.25 ,  3.125,  0.5  ,  3.   ,  1.   ,  0.25 ,
        0.25 ,  0.75 ,  2.625, 12.375,  1.375,  1.25 ,  2.75 ,  2.375,
        1.   ,  1.875,  2.   ,  2.125,  1.625,  1.625,  2.875,  2.875,
        1.875, 15.   ,  3.25 ,  2.625,  0.125,  1.   ,  1.875,  1.25 ,
        3.125,  0.5  ,  3.   ,  1.   ,  0.25 ,  0.25 ,  0.75 , 11.75 ,
       12.375, 15.125, 14.   , 13.125, 13.75 , 11.875, 14.5  , 12.   ,
       14.   , 15.25 , 15.25 , 14.25 ,  0.625,  3.375,  2.25 ,  1.625,
        2.   ,  1.625,  2.75 ,  0.75 ,  2.25 ,  3.5  ,  3.5  ,  2.5  ,
        2.75 ,  1.875,  1.5  ,  1.375,  1.75 ,  2.125,  0.375,  1.625,
        2.875,  2.875,  1.875,  1.125,  2.   ,  1.375,  3.25 ,  0.625,
        3.125,  1.125,  0.125,  0.125,  0.875,  1.625,  0.5  ,  2.125,
        1.   ,  2.   ,  1.   ,  1.25 ,  1.25 ,  0.5  ,  1.125,  1.25 ,
        1.375,  1.875,  0.875,  2.125,  2.125,  1.125,  1.875,  0.75 ,
        1.75 ,  1.   ,  1.5  ,  1.5  ,  0.5  ,  2.625,  1.875,  2.125,
        3.375,  3.375,  2.375,  2.5  ,  0.75 ,  0.75 ,  0.75 ,  0.5  ,
        2.   ,  3.25 ,  3.25 ,  2.25 ,  1.25 ,  1.25 ,  0.75 ,  0.   ,
        1.   ,  1.   ])

In [42]:
np.allclose(arr, arr.T)

True

### DURATION SIMILARITY (D2)

#### TIME BETWEEN FLIGHTS

In [43]:
dormant

,location,start,end,age,activity,tagID,duration,day,daydiff
0,Inside,2017-06-21 08:07:56.250,2017-06-21 08:11:24.300,0,inside,197,208.05,21,0
2,Inside,2017-06-21 08:28:03.650,2017-06-21 08:37:01.650,0,inside,197,538.00,21,0
4,Inside,2017-06-21 08:58:19.050,2017-06-21 09:04:15.700,0,inside,197,356.65,21,0
21,Inside,2017-06-24 09:07:51.850,2017-06-24 10:24:33.900,3,inside,197,4602.05,24,0
28,Inside,2017-06-23 09:56:07.000,2017-06-23 12:02:08.550,1,inside,508,7561.55,23,0
...,...,...,...,...,...,...,...,...,...
1812,Inside,2017-06-22 08:03:39.250,2017-06-22 08:23:36.650,0,inside,2487,1197.40,22,0
1815,Inside,2017-06-22 10:58:54.750,2017-06-22 11:11:32.800,1,inside,2487,758.05,22,0
1819,Inside,2017-06-22 15:16:52.900,2017-06-22 16:13:58.850,1,inside,2487,3425.95,22,0
1822,Inside,2017-06-23 09:38:04.300,2017-06-23 09:56:09.200,2,inside,2487,1084.90,23,0
1826,Inside,2017-06-24 09:49:40.550,2017-06-24 10:24:33.700,3,inside,2487,2093.15,24,0

In [44]:
dormant_times = dormant.groupby(['tagID'])['duration'].apply(list)
dormant_times

tagID
197                      [208.05, 538.0, 356.65, 4602.05]
508     [7561.55, 4467.3, 1363.5, 1498.35, 15145.45, 9...
515     [18.95, 8006.4, 455.35, 261.8, 18.65, 14.35, 1...
516     [4928.75, 19353.9, 5195.7, 2286.0, 564.4, 1824...
517     [11129.65, 344.35, 4728.15, 3582.75, 351.2, 32...
638     [750.0, 369.25, 302.4, 376.7, 290.8, 292.35, 2...
661                                                [69.3]
677                               [142.1, 149.45, 1024.9]
930                                             [16828.2]
1230    [426.4, 48.4, 59.65, 42.5, 66.05, 51.7, 42.2, ...
1237    [3034.45, 824.9, 22781.6, 291.0, 18593.65, 217...
1361    [85.35, 136.8, 207.1, 273.0, 196.7, 367.35, 49...
1404                                       [169.0, 458.4]
1407    [1281.45, 12649.55, 51.15, 1090.55, 2116.55, 4...
1415                                     [672.9, 1953.85]
1607    [752.8, 11.4, 286.45, 22.75, 225.4, 12.5, 650....
1609    [474.1, 26413.85, 18117.15, 307.45, 225.4, 137...
1621    [623.0, 264.85, 873.4, 2718.85, 499.55, 742.15...
1651                          [29639.4, 1091.35, 1991.75]
1652    [29359.4, 195.6, 4173.25, 188.25, 21688.2, 498...
1698    [34.1, 74.3, 25.3, 37.9, 20.75, 21.55, 193.4, ...
1722    [2312.25, 2333.25, 23116.45, 1936.6, 8648.1, 5...
1780    [21882.9, 2176.0, 15912.75, 354.4, 3087.25, 20...
1786     [15088.65, 476.45, 237.5, 404.1, 10818.8, 425.1]
1797    [551.45, 358.0, 43.95, 48.95, 3967.45, 3257.95...
1900    [16.65, 23093.85, 22.1, 1292.85, 269.85, 1217....
2258                                            [1112.05]
2487    [1383.1, 667.15, 14820.05, 95.75, 1197.4, 758....
Name: duration, dtype: object

In [45]:
arrays = [wasserstein_distance(i,j) for i in dormant_times for j in dormant_times]
arr = np.array(arrays).reshape((len(dormant_times),len(dormant_times)))
squareform(arr)

array([ 2036.4625    ,  3612.84375   ,  7002.27916667,  1378.91491935,
        1352.23308824,  1356.8875    ,  1068.52083333, 15402.0125    ,
        1406.77      ,  2034.65991379,  1092.48014706,  1112.4875    ,
        1281.4375    ,  1211.2875    ,  1345.52652439,  3673.97142857,
         656.9045    ,  9481.3125    ,  8210.8625    ,   975.34305556,
        3671.10416667,  1922.7625    ,  3169.42916667,  1397.3725    ,
        2749.34305556,  1430.8625    ,  1835.67361111,  2102.31875   ,
        5092.97166667,   789.12564516,  2063.93382353,  3267.295     ,
        2921.72833333, 13492.705     ,  2669.8275    ,  1134.33775862,
        1741.49088235,  3060.945     ,   978.62454545,  2554.2       ,
        2631.41939024,  2679.10107143,  1860.499     ,  7684.05166667,
        6353.885     ,  2870.37277778,  1956.525     ,  1141.82934783,
        1957.11166667,   909.439     ,  2200.99055556,  3015.745     ,
        1045.93055556,  3848.23541667,  2458.32883065,  3594.33933824,
        4784.14375   ,  4469.83958333, 12449.90625   ,  4040.15875   ,
        2099.06357759,  3183.83198529,  4615.28125   ,  2627.03011364,
        4470.16875   ,  4058.21458333,  2324.35982143,  3726.39325   ,
        6594.26458333,  4925.91339286,  4358.22152778,  2090.25625   ,
        2288.46331522,  1317.27291667,  2725.44525   ,  2928.91458333,
        4900.19375   ,  2823.27847222,  5648.21021505,  6995.40196078,
        8359.16666667,  7989.65      ,  9712.91666667,  7622.5175    ,
        5351.7908046 ,  6707.63431373,  8114.76666667,  6071.59621212,
        7151.25833333,  7655.96097561,  4670.3577381 ,  6751.71066667,
        4924.23333333,  3439.53333333,  7963.34444444,  3977.4       ,
        5694.95362319,  3853.36666667,  5826.88466667,  6177.63333333,
        7498.96666667,  5603.71666667,  1731.94392789,  2717.81129032,
        2357.68817204, 14047.94354839,  2168.74169355,  1215.37836485,
        1498.16432638,  2486.27580645,   551.49391496,  2016.12177419,
        2139.23693942,  2928.91422811,  1288.41296774,  8173.77150538,
        6873.26474654,  2315.73888889,  2369.18790323,  1160.79922861,
        2150.12365591,   569.94258065,  2352.16146953,  2466.20645161,
        1193.12132616,  1363.76470588,  1060.40098039, 15395.13529412,
         820.84632353,  1920.91135903,   542.79117647,  1140.18823529,
        1490.88302139,  1479.33382353,   860.87025347,  3498.08644958,
        1487.50588235,  9474.43529412,  8225.84117647,   967.94248366,
        3674.91421569,  1723.2398977 ,  3223.9372549 ,  1492.74152941,
        1822.14771242,  1434.15588235,  1508.85228758,   369.51666667,
       16758.9       ,   808.13583333,  3243.76896552,  1651.53235294,
         244.4       ,  2308.39772727,  1244.075     ,   941.39349593,
        4799.89107143,  1609.416     , 10838.2       ,  9563.14285714,
         426.63333333,  5008.85833333,  2911.36086957,  4505.8       ,
        2540.078     ,  3046.27777778,  1042.75      ,  2766.86666667,
       16389.38333333,   922.8925    ,  2882.78678161,  1446.28039216,
         252.55      ,  1993.95378788,   874.55833333,   967.23861789,
        4440.33511905,  1245.72333333, 10468.68333333,  9193.62619048,
         391.93888889,  4639.34166667,  2594.37898551,  4136.28333333,
        2196.76133333,  2725.29444444,   673.23333333,  2407.65      ,
       16106.44083333, 14130.05172414, 15107.36764706, 16514.5       ,
       14471.32954545, 15514.825     , 16096.76260163, 13790.79821429,
       15151.444     , 14461.5       , 12598.52142857, 16363.07777778,
       12798.08333333, 14314.31304348, 12253.1       , 14226.618     ,
       15138.63333333, 15716.15      , 13992.03333333,  2484.54646552,
        1023.56818627,   929.95916667,  1774.57780303,  1603.07416667,
         344.28888211,  4037.69714286,  1605.0805    , 10078.9775    ,
        8803.92035714,   600.06694444,  4249.63583333,  2126.07865942,
        3911.32583333,  1915.64483333,  2256.86861111,  1575.79083333,
        2181.34583333,  1593.22991886,  3011.84137931,  1179.23283699,
        2705.75775862,  2484.82831511,  1962.56286946,  1965.62358621,
        7598.71494253,  6320.25788177,  2847.9467433 ,  2142.5158046 ,
         606.11589205,  2434.40977011,  1199.95606897,  1189.31609195,
        3093.94310345,  1139.40153257,  1463.48529412,  1156.83890374,
        1877.14264706,  1001.34373505,  3149.50514706,  1390.91164706,
        9186.66764706,  7911.6105042 ,  1260.40424837,  3357.32598039,
        1341.86508951,  2973.34607843,  1210.85341176,  1832.91928105,
        1972.92352941,  1386.49117647,  2141.74318182,   999.675     ,
         998.0504065 ,  4572.13035714,  1372.992     , 10593.8       ,
        9318.74285714,   393.84444444,  4770.575     ,  2744.2173913 ,
        4261.4       ,  2332.638     ,  2868.34444444,   798.35      ,
        2538.74444444,  1889.65454545,  1758.38264967,  2770.77029221,
        1247.637     ,  8550.62954545,  7275.5724026 ,  1892.49368687,
        2763.15757576,   930.76966403,  2447.12954545,   705.65609091,
        1997.59974747,  2305.74318182,  1032.63055556,  1641.54085366,
        4458.95535714,   773.547     ,  9594.125     ,  8556.10357143,
        1156.775     ,  3996.89166667,  2493.14021739,  4071.525     ,
        1767.765     ,  2934.95833333,   640.475     ,  1863.20833333,
        3978.91801684,  1538.08328455,  9967.7504065 ,  8697.24610918,
         628.48807588,  4244.47296748,  2140.00318134,  3871.94796748,
        1887.46655285,  2250.73712737,  1620.63292683,  2137.38211382,
        3840.22407143,  6041.28035714,  4766.22321429,  4401.09742063,
        2910.53630952,  2274.83796584,  2539.1172619 ,  3050.84107143,
        1980.49821429,  4785.81964286,  2803.04583333,  9239.23466667,
        7974.97285714,  1211.63377778,  3427.25633333,  1789.08173913,
        3357.58466667,  1049.13      ,  2657.38      ,  1240.238     ,
        1390.172     ,  2899.07380952, 10442.37777778,  6449.88333333,
        7965.94057971,  6332.4       ,  8345.68866667,  7825.56666667,
        9809.25      ,  8071.33333333,  9167.32063492,  5033.1047619 ,
        6679.01677019,  5088.65952381,  7034.78942857,  6550.50952381,
        9106.02857143,  6998.29047619,  4613.03611111,  2490.46425121,
        4109.97777778,  2136.45977778,  2622.48888889,  1048.98333333,
        2371.04444444,  2227.87101449,  2572.75      ,  2480.36433333,
        2794.23888889,  4436.60833333,  2699.37777778,  2535.37536232,
        1088.91521739,  1382.01352657,  2950.61521739,  1133.97681159,
        2504.22133333,  3467.52777778,  4431.4       ,  2408.57222222,
        2222.97044444,  2278.816     ,  1096.26155556,  2978.61666667,
        1592.85555556,  2133.52777778])

In [46]:
np.allclose(arr, arr.T)

True

#### DURATION OF FLIGHTS

In [47]:
active_times = flights.groupby(['tagID'])['duration'].apply(list)
active_times

tagID
197                    [999.35, 1277.4, 5677.9, 19203.15]
508     [6911.35, 2958.65, 3368.35, 5936.05, 1675.5, 1...
515     [30.9, 88.2, 12807.25, 170.4, 3882.5, 61.4, 11...
516     [71.2, 79.4, 118.0, 55.0, 27.25, 38.85, 60.6, ...
517     [77.0, 1031.85, 1421.25, 1829.0, 49.2, 472.15,...
638     [1948.55, 1099.05, 1148.3, 1905.55, 1581.7, 85...
661                                             [8158.35]
677                              [1996.2, 3284.8, 7581.4]
1230    [748.6, 33.8, 44.6, 204.95, 31.5, 27.75, 18.2,...
1237    [767.2, 642.3, 170.35, 2405.9, 5337.4, 1595.85...
1361    [1413.85, 4987.5, 13.0, 571.8, 8565.75, 5358.3...
1404                              [146.75, 889.75, 962.6]
1407    [75.85, 639.75, 470.85, 104.1, 97.65, 10.2, 69...
1415                             [5723.9, 1507.7, 3281.6]
1607    [19.8, 13.75, 26.45, 32.75, 23.3, 20.1, 26.6, ...
1609    [1414.3, 24.1, 738.75, 3233.3, 1332.25, 2515.7...
1621    [854.4, 1013.6, 2159.55, 2792.05, 3506.2, 276....
1651                                      [127.05, 163.5]
1652    [1836.15, 2292.8, 2250.65, 75.0, 1264.0, 1358....
1698    [30.25, 18.2, 42.4, 17.05, 19.7, 17.9, 28.3, 1...
1722    [3432.6, 5040.8, 2227.5, 2938.15, 3237.55, 270...
1780    [61.8, 53.6, 42.15, 59.65, 37.6, 165.05, 41.0,...
1786    [4484.4, 4285.0, 1305.45, 1341.4, 4545.8, 6376...
1797    [61.55, 16.6, 18.25, 12.45, 1899.2, 43.45, 545...
1900    [70.2, 79.8, 51.75, 65.4, 56.2, 80.5, 17.0, 39...
1979                                              [125.9]
2258                                            [14783.6]
2487    [2215.5, 1906.3, 1278.6, 24.75, 3283.2, 7603.4...
Name: duration, dtype: object

In [48]:
arrays = [wasserstein_distance(i,j) for i in active_times for j in active_times]
arr = np.array(arrays).reshape((len(active_times),len(active_times)))
squareform(arr)

array([3.62078750e+03, 3.14412857e+03, 6.72987778e+03, 6.01689028e+03,
       5.49105500e+03, 6.89130000e+03, 4.10659167e+03, 6.62237667e+03,
       4.75179286e+03, 3.40683553e+03, 6.12308333e+03, 5.96965833e+03,
       4.25334167e+03, 6.64247886e+03, 5.66237586e+03, 4.56171458e+03,
       6.64417500e+03, 4.80895682e+03, 6.75605556e+03, 3.92960962e+03,
       6.16673750e+03, 3.97769643e+03, 5.01067593e+03, 6.74125000e+03,
       6.66355000e+03, 1.02039250e+04, 4.47856389e+03, 2.76760298e+03,
       4.46969028e+03, 3.75670278e+03, 3.23086750e+03, 4.31622917e+03,
       1.04323750e+03, 4.36218917e+03, 2.49160536e+03, 1.70391952e+03,
       3.86289583e+03, 3.70947083e+03, 1.07868750e+03, 4.38229136e+03,
       3.40218836e+03, 2.12683125e+03, 4.38398750e+03, 2.49028977e+03,
       4.49586806e+03, 7.36980449e+02, 3.90655000e+03, 1.41688393e+03,
       2.74312361e+03, 4.48106250e+03, 4.40336250e+03, 1.02543375e+04,
       2.06636806e+03, 3.98596667e+03, 3.56754702e+03, 3.55290143e+03,
       6.33202857e+03, 2.90467857e+03, 3.87806238e+03, 2.86100357e+03,
       2.52995000e+03, 3.80003571e+03, 3.22534405e+03, 3.18365000e+03,
       3.89816458e+03, 3.29455123e+03, 2.85812232e+03, 3.95718929e+03,
       3.11537662e+03, 4.01174127e+03, 3.06679011e+03, 3.42242321e+03,
       3.04231429e+03, 2.69876349e+03, 3.99693571e+03, 3.97557857e+03,
       1.07384643e+04, 2.63478968e+03, 7.13037500e+02, 1.23946278e+03,
       8.09877778e+03, 4.22789444e+03, 1.29298333e+02, 1.97808492e+03,
       4.59561725e+03, 6.06794444e+02, 7.66505556e+02, 3.44482778e+03,
       1.16501626e+02, 1.07291073e+03, 2.34470625e+03, 8.57027778e+01,
       1.98156869e+03, 2.61777778e+01, 4.30045470e+03, 5.66396230e+02,
       3.26772063e+03, 1.73302593e+03, 1.17439394e+01, 6.63277778e+01,
       1.47240278e+04, 2.44232778e+03, 5.74464167e+02, 7.38579028e+03,
       3.51490694e+03, 6.51708056e+02, 1.26509742e+03, 3.88354759e+03,
       2.36145833e+02, 5.43294444e+02, 2.73184028e+03, 6.25588584e+02,
       3.75812404e+02, 1.63362014e+03, 6.71676389e+02, 1.26858119e+03,
       7.39165278e+02, 3.58746720e+03, 5.64829762e+02, 2.55473313e+03,
       1.03945046e+03, 7.24359722e+02, 6.90348611e+02, 1.40110403e+04,
       1.73109583e+03, 6.85995500e+03, 2.98907167e+03, 1.20554333e+03,
       7.91147857e+02, 3.40854421e+03, 6.56568333e+02, 8.44001667e+02,
       2.20600500e+03, 1.15142386e+03, 4.01434483e+02, 1.17874042e+03,
       1.17372000e+03, 7.51165000e+02, 1.26500056e+03, 3.06163192e+03,
       1.02029393e+03, 2.02889786e+03, 9.43441667e+02, 1.25019500e+03,
       1.19286500e+03, 1.34852050e+04, 1.37675111e+03, 3.87088333e+03,
       7.99127667e+03, 6.16562857e+03, 3.88599211e+03, 7.49198333e+03,
       7.33855833e+03, 4.65395000e+03, 8.01137886e+03, 7.03127586e+03,
       5.75591875e+03, 8.01307500e+03, 6.11720909e+03, 8.12495556e+03,
       4.70470000e+03, 7.53563750e+03, 4.83105714e+03, 6.38296296e+03,
       8.11015000e+03, 8.03245000e+03, 6.62525000e+03, 5.65700556e+03,
       4.12039333e+03, 2.33595595e+03, 1.45255263e+03, 3.62110000e+03,
       3.46767500e+03, 7.83066667e+02, 4.14049553e+03, 3.16039253e+03,
       1.88503542e+03, 4.14219167e+03, 2.24632576e+03, 4.25407222e+03,
       1.56800385e+03, 3.66475417e+03, 1.47444048e+03, 2.55481667e+03,
       4.23926667e+03, 4.16156667e+03, 1.04961333e+04, 1.79102222e+03,
       1.87058381e+03, 4.48661614e+03, 6.32885000e+02, 6.79978333e+02,
       3.33732667e+03, 9.80537398e+01, 1.00584414e+03, 2.23535792e+03,
       1.92700000e+02, 1.87406758e+03, 1.33725556e+02, 4.19295359e+03,
       4.55639167e+02, 3.16021952e+03, 1.61906556e+03, 1.27724545e+02,
       1.85648333e+02, 1.46165267e+04, 2.33427111e+03, 2.70019718e+03,
       1.37129048e+03, 1.21786548e+03, 1.69307857e+03, 1.89068600e+03,
       9.10583005e+02, 6.97627679e+02, 1.89238214e+03, 5.42683766e+02,
       2.00426270e+03, 2.32236978e+03, 1.41494464e+03, 1.46186786e+03,
       4.68644974e+02, 1.98945714e+03, 1.91175714e+03, 1.27459429e+04,
       7.65718254e+02, 4.01333333e+03, 3.83389781e+03, 1.85451053e+03,
       4.50672711e+03, 3.52678993e+03, 2.32004726e+03, 4.53027763e+03,
       2.69430407e+03, 4.62029503e+03, 2.17289049e+03, 4.03098224e+03,
       1.67092293e+03, 2.86759113e+03, 4.60548947e+03, 4.54941053e+03,
       1.01299105e+04, 2.18714561e+03, 7.56645833e+02, 2.83803333e+03,
       5.64319919e+02, 5.85878736e+02, 1.76732292e+03, 5.21091667e+02,
       1.38781970e+03, 6.32972222e+02, 3.69366026e+03, 7.42929167e+02,
       2.66092619e+03, 1.23564259e+03, 6.18166667e+02, 5.40466667e+02,
       1.41172333e+04, 1.87713333e+03, 2.68460833e+03, 6.73342581e+02,
       4.59026006e+02, 1.58263958e+03, 7.64025000e+02, 1.24979470e+03,
       7.86677778e+02, 3.54023526e+03, 3.04126786e+02, 2.50750119e+03,
       9.69730556e+02, 7.71891288e+02, 7.75983333e+02, 1.39638083e+04,
       1.68155278e+03, 3.35742886e+03, 2.37732586e+03, 1.25920208e+03,
       3.35912500e+03, 1.70517727e+03, 3.47100556e+03, 1.32302436e+03,
       2.88168750e+03, 8.79269048e+02, 1.90934259e+03, 3.45620000e+03,
       3.37850000e+03, 1.12792000e+04, 1.42073333e+03, 9.80103000e+02,
       2.25546052e+03, 1.77725813e+02, 1.89416977e+03, 1.13610027e+02,
       4.21305578e+03, 4.75771443e+02, 3.18032172e+03, 1.63918085e+03,
       1.14626644e+02, 1.71154878e+02, 1.46366289e+04, 2.35437331e+03,
       1.27547205e+03, 1.02740603e+03, 9.17131348e+02, 1.09367969e+03,
       3.23295279e+03, 7.08567796e+02, 2.20021872e+03, 7.27034100e+02,
       1.07887414e+03, 1.04622586e+03, 1.36565259e+04, 1.37537835e+03,
       2.28348958e+03, 5.87311174e+02, 2.36903681e+03, 1.96760208e+03,
       1.77982470e+03, 1.05833720e+03, 7.11840046e+02, 2.35423125e+03,
       2.30257708e+03, 1.23811688e+04, 3.99734028e+02, 1.90532955e+03,
       1.11880556e+02, 4.21475192e+03, 5.84951786e+02, 3.18201786e+03,
       1.70674167e+03, 9.70750000e+01, 1.93750000e+01, 1.46383250e+04,
       2.38946944e+03, 2.00774646e+03, 2.36355734e+03, 1.41842841e+03,
       1.41164545e+03, 6.84751515e+02, 1.99294091e+03, 1.92449545e+03,
       1.27424591e+04, 6.68996465e+02, 4.32663248e+03, 5.89318056e+02,
       3.29389841e+03, 1.75274444e+03, 1.89333333e+01, 9.25055556e+01,
       1.47502056e+04, 2.46795000e+03, 3.73731442e+03, 1.42774176e+03,
       2.57388803e+03, 4.31182692e+03, 4.23412692e+03, 1.04235731e+04,
       2.00541752e+03, 2.70458036e+03, 1.16680655e+03, 5.74512500e+02,
       5.92433929e+02, 1.41608875e+04, 1.87874623e+03, 1.68391693e+03,
       3.27909286e+03, 3.20139286e+03, 1.14563071e+04, 1.17636587e+03,
       1.73795673e+03, 1.72535000e+03, 1.29974611e+04, 7.67061111e+02,
       7.77000000e+01, 1.47354000e+04, 2.45314444e+03, 1.46577000e+04,
       2.40833333e+03, 1.22822556e+04])

In [49]:
np.allclose(arr, arr.T)

True

### SCHEDULE SIMILARITY (D3)

Bin calculation

In [50]:
active_times

tagID
197                    [999.35, 1277.4, 5677.9, 19203.15]
508     [6911.35, 2958.65, 3368.35, 5936.05, 1675.5, 1...
515     [30.9, 88.2, 12807.25, 170.4, 3882.5, 61.4, 11...
516     [71.2, 79.4, 118.0, 55.0, 27.25, 38.85, 60.6, ...
517     [77.0, 1031.85, 1421.25, 1829.0, 49.2, 472.15,...
638     [1948.55, 1099.05, 1148.3, 1905.55, 1581.7, 85...
661                                             [8158.35]
677                              [1996.2, 3284.8, 7581.4]
1230    [748.6, 33.8, 44.6, 204.95, 31.5, 27.75, 18.2,...
1237    [767.2, 642.3, 170.35, 2405.9, 5337.4, 1595.85...
1361    [1413.85, 4987.5, 13.0, 571.8, 8565.75, 5358.3...
1404                              [146.75, 889.75, 962.6]
1407    [75.85, 639.75, 470.85, 104.1, 97.65, 10.2, 69...
1415                             [5723.9, 1507.7, 3281.6]
1607    [19.8, 13.75, 26.45, 32.75, 23.3, 20.1, 26.6, ...
1609    [1414.3, 24.1, 738.75, 3233.3, 1332.25, 2515.7...
1621    [854.4, 1013.6, 2159.55, 2792.05, 3506.2, 276....
1651                                      [127.05, 163.5]
1652    [1836.15, 2292.8, 2250.65, 75.0, 1264.0, 1358....
1698    [30.25, 18.2, 42.4, 17.05, 19.7, 17.9, 28.3, 1...
1722    [3432.6, 5040.8, 2227.5, 2938.15, 3237.55, 270...
1780    [61.8, 53.6, 42.15, 59.65, 37.6, 165.05, 41.0,...
1786    [4484.4, 4285.0, 1305.45, 1341.4, 4545.8, 6376...
1797    [61.55, 16.6, 18.25, 12.45, 1899.2, 43.45, 545...
1900    [70.2, 79.8, 51.75, 65.4, 56.2, 80.5, 17.0, 39...
1979                                              [125.9]
2258                                            [14783.6]
2487    [2215.5, 1906.3, 1278.6, 24.75, 3283.2, 7603.4...
Name: duration, dtype: object

In [51]:
bins = pd.Series([x for xs in active_times for x in xs]).apply(
    lambda x: 5 if x <= 300 else
    10 if x <= 600 else
    15 if x <= 900 else
    20 if x <= 1200 else
    30 if x <= 1800 else
    60
)

bins

0      20
1      30
2      60
3      60
4      60
       ..
528    60
529    60
530    30
531    60
532     5
Length: 533, dtype: int64

In [52]:
bins.groupby(bins).size()

5     289
10     16
15     36
20     35
30     41
60    116
dtype: int64

Using 5 minute bins

In [53]:
flights_count = flights_count.sort_values(['day','5minute'])
count = flights_count.groupby(['tagID','date','5minute']).size()
idx = pd.MultiIndex.from_product([flights_count.tagID.unique(), flights_count.day.unique(), flights_count['20minute'].unique()])
count = count.reindex(idx).fillna(0)
count
#unstacked = count.unstack(['day','20minute'], fill_value=0)
#unstacked_dict = unstacked.groupby(level=0).apply(lambda df: df.xs(df.name).to_dict()).to_dict()

516  21  8.000000     0.0
         8.333333     0.0
         8.666667     0.0
         9.000000     0.0
         9.333333     0.0
                     ...
661  28  18.000000    0.0
         18.333333    0.0
         18.666667    0.0
         19.333333    0.0
         19.666667    0.0
Length: 7840, dtype: float64

In [54]:
result = {
    tag: {
        day: g.values.tolist()
        for day, g in tag_group.groupby(level=1)
    }
    for tag, tag_group in count.groupby(level=0)
}
result

{197: {21: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  22: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  23: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  24: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  25: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  26: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  27: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  28: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0]},
 508: {21: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  22: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  23: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  24: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  25: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  26: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  27: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  28: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0]},
 515: {21: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  22: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  23: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  24: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  25: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  26: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  27: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  28: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0]},
 516: {21: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  22: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  23: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  24: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  25: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  26: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  27: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  28: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0]},
 517: {21: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  22: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  23: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  24: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  25: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  26: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  27: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  28: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0]},
 638: {21: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  22: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  23: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  24: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  25: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  26: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  27: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  28: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0]},
 661: {21: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  22: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  23: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  24: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  25: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  26: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  27: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  28: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0]},
 677: {21: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  22: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  23: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  24: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  25: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  26: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  27: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  28: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0]},
 1230: {21: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  22: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  23: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  24: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  25: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  26: [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,

In [55]:
def compareScheduleDaytoDay(tag1, tag2, result):
    bee1 = result[tag1]
    bee2 = result[tag2]
    values = []
    for (k,v), (k2,v2) in zip(bee1.items(), bee2.items()):
        cosine = np.dot(v, v2) / (norm(v) * norm(v2))
        values.append(cosine)
    return np.nan_to_num(values)

compareScheduleDaytoDay(1621,1361,result)

C:\Users\kashi\AppData\Local\Temp\ipykernel_2212\371221653.py:6: RuntimeWarning: invalid value encountered in scalar divide
  cosine = np.dot(v, v2) / (norm(v) * norm(v2))

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [56]:
result_mat = {}
for key,val in result.items():
    mat = []
    for day, lst in val.items():
        mat.append(lst)
    npmat = np.array([np.array(xi) for xi in mat])
    result_mat[key] = npmat

result_mat

{197: array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.]]),
 508: array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.]]),
 515: array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.]]),
 516: array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.]]),
 517: array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.]]),
 638: array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.]]),
 661: array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.]]),
 677: array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.]]),
 1230: array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.]]),
 1237: array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.]]),
 1361: array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.]]),
 1404: array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.]]),
 1407: array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.]]),
 1415: array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.]]),
 1607: array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],

In [57]:
def compareMatrixes(tag1,tag2,result):
    bee1 = result[tag1]
    bee2 = result[tag2]
    return cosine_similarity(bee1,bee2)

np.triu(compareMatrixes(1621,1361,result_mat))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

### TREND SIMILARITY (D4)

#### FLIGHT FREQUENCY

In [58]:
from sklearn.linear_model import LinearRegression

In [59]:
flights_nofill

date   06/21  06/22  06/23  06/24  06/25  06/26  06/27  06/28
tagID
197      3.0    NaN    NaN    1.0    NaN    NaN    NaN    NaN
508      1.0    NaN    NaN    1.0    2.0    2.0    5.0    1.0
515      3.0    2.0    1.0    NaN    NaN    NaN    1.0    NaN
516      1.0    1.0    2.0    1.0    1.0    1.0    1.0    1.0
517      4.0    8.0    7.0    2.0    2.0    7.0    6.0    NaN
638      4.0    4.0    4.0    3.0    NaN    2.0    3.0    NaN
661      NaN    1.0    NaN    NaN    NaN    NaN    NaN    NaN
677      3.0    NaN    NaN    NaN    NaN    NaN    NaN    NaN
1230    39.0    2.0   19.0    NaN    NaN    NaN    NaN    NaN
1237     3.0    3.0    5.0    2.0    3.0    4.0    8.0    NaN
1361     5.0    1.0    3.0    1.0    2.0    2.0    5.0    NaN
1404     3.0    NaN    NaN    NaN    NaN    NaN    NaN    NaN
1407     9.0    9.0    3.0    3.0    NaN    NaN    NaN    NaN
1415     1.0    2.0    NaN    NaN    NaN    NaN    NaN    NaN
1607    24.0    6.0   23.0    4.0    5.0   21.0   14.0   26.0
1609     2.0    1.0    9.0    4.0    6.0    2.0    5.0    NaN
1621     6.0    3.0    5.0    1.0    7.0    2.0    NaN    NaN
1651     2.0    NaN    NaN    NaN    NaN    NaN    NaN    NaN
1652     2.0    1.0    1.0    1.0    2.0    1.0    3.0    NaN
1698    10.0    2.0    2.0    4.0    NaN    NaN    NaN    NaN
1722     1.0    3.0    NaN    2.0    2.0    1.0    4.0    NaN
1780     1.0    2.0    2.0    1.0    NaN   15.0    3.0    4.0
1786     4.0    3.0    NaN    NaN    NaN    NaN    NaN    NaN
1797     5.0    3.0    1.0    1.0    6.0    3.0    7.0    1.0
1900     1.0    1.0    2.0    7.0    NaN    NaN    NaN    NaN
1979     1.0    NaN    NaN    NaN    NaN    NaN    NaN    NaN
2258     NaN    1.0    NaN    NaN    NaN    NaN    NaN    NaN
2487     3.0    3.0    1.0    2.0    NaN    NaN    NaN    NaN

In [60]:
reg = flights_nofill.apply(
    lambda x: [(d,v) for d,v in x.items() if pd.notna(v)],
    axis=1
)
reg

tagID
197                          [(06/21, 3.0), (06/24, 1.0)]
508     [(06/21, 1.0), (06/24, 1.0), (06/25, 2.0), (06...
515     [(06/21, 3.0), (06/22, 2.0), (06/23, 1.0), (06...
516     [(06/21, 1.0), (06/22, 1.0), (06/23, 2.0), (06...
517     [(06/21, 4.0), (06/22, 8.0), (06/23, 7.0), (06...
638     [(06/21, 4.0), (06/22, 4.0), (06/23, 4.0), (06...
661                                        [(06/22, 1.0)]
677                                        [(06/21, 3.0)]
1230         [(06/21, 39.0), (06/22, 2.0), (06/23, 19.0)]
1237    [(06/21, 3.0), (06/22, 3.0), (06/23, 5.0), (06...
1361    [(06/21, 5.0), (06/22, 1.0), (06/23, 3.0), (06...
1404                                       [(06/21, 3.0)]
1407    [(06/21, 9.0), (06/22, 9.0), (06/23, 3.0), (06...
1415                         [(06/21, 1.0), (06/22, 2.0)]
1607    [(06/21, 24.0), (06/22, 6.0), (06/23, 23.0), (...
1609    [(06/21, 2.0), (06/22, 1.0), (06/23, 9.0), (06...
1621    [(06/21, 6.0), (06/22, 3.0), (06/23, 5.0), (06...
1651                                       [(06/21, 2.0)]
1652    [(06/21, 2.0), (06/22, 1.0), (06/23, 1.0), (06...
1698    [(06/21, 10.0), (06/22, 2.0), (06/23, 2.0), (0...
1722    [(06/21, 1.0), (06/22, 3.0), (06/24, 2.0), (06...
1780    [(06/21, 1.0), (06/22, 2.0), (06/23, 2.0), (06...
1786                         [(06/21, 4.0), (06/22, 3.0)]
1797    [(06/21, 5.0), (06/22, 3.0), (06/23, 1.0), (06...
1900    [(06/21, 1.0), (06/22, 1.0), (06/23, 2.0), (06...
1979                                       [(06/21, 1.0)]
2258                                       [(06/22, 1.0)]
2487    [(06/21, 3.0), (06/22, 3.0), (06/23, 1.0), (06...
dtype: object

In [61]:
days = pd.Series(np.sort(flights['date'].unique()))
day_map = dict(zip(days, days.astype('category').cat.codes))
day_map

{'06/21': 0,
 '06/22': 1,
 '06/23': 2,
 '06/24': 3,
 '06/25': 4,
 '06/26': 5,
 '06/27': 6,
 '06/28': 7}

In [62]:
regs = {}
for index, val in reg.items():
    x = []
    y = []
    for v in val:
        x.append(day_map[v[0]])
        y.append(v[1])
    x = np.array(x).reshape([-1,1])
    linreg = LinearRegression().fit(x, y)
    slope = linreg.coef_
    regs[index] = slope

regs = pd.Series(regs)
regs

197      [-0.6666666666666665]
508       [0.2594594594594595]
515      [-0.2771084337349398]
516     [-0.03571428571428572]
517     [-0.03571428571428576]
638     [-0.28571428571428575]
661                      [0.0]
677                      [0.0]
1230      [-9.999999999999995]
1237      [0.5357142857142857]
1361     [0.03571428571428568]
1404                     [0.0]
1407     [-2.3999999999999995]
1415      [0.9999999999999998]
1607      [0.5833333333333334]
1609     [0.28571428571428564]
1621    [-0.34285714285714297]
1651                     [0.0]
1652     [0.14285714285714282]
1698     [-1.7999999999999998]
1722     [0.18012422360248453]
1780      [0.8150684931506852]
1786     [-0.9999999999999998]
1797    [0.035714285714285705]
1900                     [1.9]
1979                     [0.0]
2258                     [0.0]
2487    [-0.49999999999999983]
dtype: object

In [63]:
arrays = [abs(i-j) for index,i in regs.items() for index2, j in regs.items()]
arr = np.array(arrays).reshape((len(regs),len(regs)))
squareform(arr)

array([9.26126126e-01, 3.89558233e-01, 6.30952381e-01, 6.30952381e-01,
       3.80952381e-01, 6.66666667e-01, 6.66666667e-01, 9.33333333e+00,
       1.20238095e+00, 7.02380952e-01, 6.66666667e-01, 1.73333333e+00,
       1.66666667e+00, 1.25000000e+00, 9.52380952e-01, 3.23809524e-01,
       6.66666667e-01, 8.09523810e-01, 1.13333333e+00, 8.46790890e-01,
       1.48173516e+00, 3.33333333e-01, 7.02380952e-01, 2.56666667e+00,
       6.66666667e-01, 6.66666667e-01, 1.66666667e-01, 5.36567893e-01,
       2.95173745e-01, 2.95173745e-01, 5.45173745e-01, 2.59459459e-01,
       2.59459459e-01, 1.02594595e+01, 2.76254826e-01, 2.23745174e-01,
       2.59459459e-01, 2.65945946e+00, 7.40540541e-01, 3.23873874e-01,
       2.62548263e-02, 6.02316602e-01, 2.59459459e-01, 1.16602317e-01,
       2.05945946e+00, 7.93352359e-02, 5.55609034e-01, 1.25945946e+00,
       2.23745174e-01, 1.64054054e+00, 2.59459459e-01, 2.59459459e-01,
       7.59459459e-01, 2.41394148e-01, 2.41394148e-01, 8.60585198e-03,
       2.77108434e-01, 2.77108434e-01, 9.72289157e+00, 8.12822719e-01,
       3.12822719e-01, 2.77108434e-01, 2.12289157e+00, 1.27710843e+00,
       8.60441767e-01, 5.62822719e-01, 6.57487091e-02, 2.77108434e-01,
       4.19965577e-01, 1.52289157e+00, 4.57232657e-01, 1.09217693e+00,
       7.22891566e-01, 3.12822719e-01, 2.17710843e+00, 2.77108434e-01,
       2.77108434e-01, 2.22891566e-01, 4.16333634e-17, 2.50000000e-01,
       3.57142857e-02, 3.57142857e-02, 9.96428571e+00, 5.71428571e-01,
       7.14285714e-02, 3.57142857e-02, 2.36428571e+00, 1.03571429e+00,
       6.19047619e-01, 3.21428571e-01, 3.07142857e-01, 3.57142857e-02,
       1.78571429e-01, 1.76428571e+00, 2.15838509e-01, 8.50782779e-01,
       9.64285714e-01, 7.14285714e-02, 1.93571429e+00, 3.57142857e-02,
       3.57142857e-02, 4.64285714e-01, 2.50000000e-01, 3.57142857e-02,
       3.57142857e-02, 9.96428571e+00, 5.71428571e-01, 7.14285714e-02,
       3.57142857e-02, 2.36428571e+00, 1.03571429e+00, 6.19047619e-01,
       3.21428571e-01, 3.07142857e-01, 3.57142857e-02, 1.78571429e-01,
       1.76428571e+00, 2.15838509e-01, 8.50782779e-01, 9.64285714e-01,
       7.14285714e-02, 1.93571429e+00, 3.57142857e-02, 3.57142857e-02,
       4.64285714e-01, 2.85714286e-01, 2.85714286e-01, 9.71428571e+00,
       8.21428571e-01, 3.21428571e-01, 2.85714286e-01, 2.11428571e+00,
       1.28571429e+00, 8.69047619e-01, 5.71428571e-01, 5.71428571e-02,
       2.85714286e-01, 4.28571429e-01, 1.51428571e+00, 4.65838509e-01,
       1.10078278e+00, 7.14285714e-01, 3.21428571e-01, 2.18571429e+00,
       2.85714286e-01, 2.85714286e-01, 2.14285714e-01, 0.00000000e+00,
       1.00000000e+01, 5.35714286e-01, 3.57142857e-02, 0.00000000e+00,
       2.40000000e+00, 1.00000000e+00, 5.83333333e-01, 2.85714286e-01,
       3.42857143e-01, 0.00000000e+00, 1.42857143e-01, 1.80000000e+00,
       1.80124224e-01, 8.15068493e-01, 1.00000000e+00, 3.57142857e-02,
       1.90000000e+00, 0.00000000e+00, 0.00000000e+00, 5.00000000e-01,
       1.00000000e+01, 5.35714286e-01, 3.57142857e-02, 0.00000000e+00,
       2.40000000e+00, 1.00000000e+00, 5.83333333e-01, 2.85714286e-01,
       3.42857143e-01, 0.00000000e+00, 1.42857143e-01, 1.80000000e+00,
       1.80124224e-01, 8.15068493e-01, 1.00000000e+00, 3.57142857e-02,
       1.90000000e+00, 0.00000000e+00, 0.00000000e+00, 5.00000000e-01,
       1.05357143e+01, 1.00357143e+01, 1.00000000e+01, 7.60000000e+00,
       1.10000000e+01, 1.05833333e+01, 1.02857143e+01, 9.65714286e+00,
       1.00000000e+01, 1.01428571e+01, 8.20000000e+00, 1.01801242e+01,
       1.08150685e+01, 9.00000000e+00, 1.00357143e+01, 1.19000000e+01,
       1.00000000e+01, 1.00000000e+01, 9.50000000e+00, 5.00000000e-01,
       5.35714286e-01, 2.93571429e+00, 4.64285714e-01, 4.76190476e-02,
       2.50000000e-01, 8.78571429e-01, 5.35714286e-01, 3.92857143e-01,
       2.33571429e+00, 3.55590062e-01, 2.79354207e-01, 1.53571429e+00,
       5.00000000e-01, 1.36428571e+00, 5.35714286e-01, 5.35714286e-01,
       1.03571429e+00, 3.57142857e-02, 2.43571429e+00, 9.64285714e-01,
       5.47619048e-01, 2.50000000e-01, 3.78571429e-01, 3.57142857e-02,
       1.07142857e-01, 1.83571429e+00, 1.44409938e-01, 7.79354207e-01,
       1.03571429e+00, 2.77555756e-17, 1.86428571e+00, 3.57142857e-02,
       3.57142857e-02, 5.35714286e-01, 2.40000000e+00, 1.00000000e+00,
       5.83333333e-01, 2.85714286e-01, 3.42857143e-01, 0.00000000e+00,
       1.42857143e-01, 1.80000000e+00, 1.80124224e-01, 8.15068493e-01,
       1.00000000e+00, 3.57142857e-02, 1.90000000e+00, 0.00000000e+00,
       0.00000000e+00, 5.00000000e-01, 3.40000000e+00, 2.98333333e+00,
       2.68571429e+00, 2.05714286e+00, 2.40000000e+00, 2.54285714e+00,
       6.00000000e-01, 2.58012422e+00, 3.21506849e+00, 1.40000000e+00,
       2.43571429e+00, 4.30000000e+00, 2.40000000e+00, 2.40000000e+00,
       1.90000000e+00, 4.16666667e-01, 7.14285714e-01, 1.34285714e+00,
       1.00000000e+00, 8.57142857e-01, 2.80000000e+00, 8.19875776e-01,
       1.84931507e-01, 2.00000000e+00, 9.64285714e-01, 9.00000000e-01,
       1.00000000e+00, 1.00000000e+00, 1.50000000e+00, 2.97619048e-01,
       9.26190476e-01, 5.83333333e-01, 4.40476190e-01, 2.38333333e+00,
       4.03209110e-01, 2.31735160e-01, 1.58333333e+00, 5.47619048e-01,
       1.31666667e+00, 5.83333333e-01, 5.83333333e-01, 1.08333333e+00,
       6.28571429e-01, 2.85714286e-01, 1.42857143e-01, 2.08571429e+00,
       1.05590062e-01, 5.29354207e-01, 1.28571429e+00, 2.50000000e-01,
       1.61428571e+00, 2.85714286e-01, 2.85714286e-01, 7.85714286e-01,
       3.42857143e-01, 4.85714286e-01, 1.45714286e+00, 5.22981366e-01,
       1.15792564e+00, 6.57142857e-01, 3.78571429e-01, 2.24285714e+00,
       3.42857143e-01, 3.42857143e-01, 1.57142857e-01, 1.42857143e-01,
       1.80000000e+00, 1.80124224e-01, 8.15068493e-01, 1.00000000e+00,
       3.57142857e-02, 1.90000000e+00, 0.00000000e+00, 0.00000000e+00,
       5.00000000e-01, 1.94285714e+00, 3.72670807e-02, 6.72211350e-01,
       1.14285714e+00, 1.07142857e-01, 1.75714286e+00, 1.42857143e-01,
       1.42857143e-01, 6.42857143e-01, 1.98012422e+00, 2.61506849e+00,
       8.00000000e-01, 1.83571429e+00, 3.70000000e+00, 1.80000000e+00,
       1.80000000e+00, 1.30000000e+00, 6.34944270e-01, 1.18012422e+00,
       1.44409938e-01, 1.71987578e+00, 1.80124224e-01, 1.80124224e-01,
       6.80124224e-01, 1.81506849e+00, 7.79354207e-01, 1.08493151e+00,
       8.15068493e-01, 8.15068493e-01, 1.31506849e+00, 1.03571429e+00,
       2.90000000e+00, 1.00000000e+00, 1.00000000e+00, 5.00000000e-01,
       1.86428571e+00, 3.57142857e-02, 3.57142857e-02, 5.35714286e-01,
       1.90000000e+00, 1.90000000e+00, 2.40000000e+00, 0.00000000e+00,
       5.00000000e-01, 5.00000000e-01])

#### FLIGHT DURATION

In [64]:
dur_nofill = flights.groupby(['tagID','date'])['duration'].agg("mean").unstack()
regDur = dur_nofill.apply(
    lambda x: [(d,v) for d,v in x.items() if pd.notna(v)],
    axis=1
)

In [65]:
regsDur = {}
for index, val in regDur.items():
    x = []
    y = []
    for v in val:
        x.append(day_map[v[0]])
        y.append(v[1])
    x = np.array(x).reshape([-1,1])
    linreg = LinearRegression().fit(x, y)
    slope = linreg.coef_
    regsDur[index] = slope

regsDur = pd.Series(regsDur)
regsDur

197                  [5517.2]
508     [-325.33556756756764]
515      [1447.6722891566262]
516      [-5.449404761904763]
517     [-17.394642857142877]
638      [-89.65527950310559]
661                     [0.0]
677                     [0.0]
1230     [124.22705802968956]
1237             [168.664375]
1361      [403.6204166666664]
1404                    [0.0]
1407      [1050.171111111111]
1415    [-3329.2499999999977]
1607    [-22.366438620041112]
1609     [20.008908730158744]
1621      [555.8883129251701]
1651                    [0.0]
1652      [91.07857142857131]
1698                  [9.942]
1722      [287.0589285714285]
1780     [271.39392123287683]
1786     [1104.2041666666662]
1797       [159.994149659864]
1900    [-11.908928571428572]
1979                    [0.0]
2258                    [0.0]
2487    [-61.173333333333304]
dtype: object

In [66]:
arrays = [abs(i-j) for index,i in regsDur.items() for index2, j in regsDur.items()]
arr = np.array(arrays).reshape((len(regsDur),len(regsDur)))
squareform(arr)

array([5.84253557e+03, 4.06952771e+03, 5.52264940e+03, 5.53459464e+03,
       5.60685528e+03, 5.51720000e+03, 5.51720000e+03, 5.39297294e+03,
       5.34853562e+03, 5.11357958e+03, 5.51720000e+03, 4.46702889e+03,
       8.84645000e+03, 5.53956644e+03, 5.49719109e+03, 4.96131169e+03,
       5.51720000e+03, 5.42612143e+03, 5.50725800e+03, 5.23014107e+03,
       5.24580608e+03, 4.41299583e+03, 5.35720585e+03, 5.52910893e+03,
       5.51720000e+03, 5.51720000e+03, 5.57837333e+03, 1.77300786e+03,
       3.19886163e+02, 3.07940925e+02, 2.35680288e+02, 3.25335568e+02,
       3.25335568e+02, 4.49562626e+02, 4.93999943e+02, 7.28955984e+02,
       3.25335568e+02, 1.37550668e+03, 3.00391443e+03, 3.02969129e+02,
       3.45344476e+02, 8.81223880e+02, 3.25335568e+02, 4.16414139e+02,
       3.35277568e+02, 6.12394496e+02, 5.96729489e+02, 1.42953973e+03,
       4.85329717e+02, 3.13426639e+02, 3.25335568e+02, 3.25335568e+02,
       2.64162234e+02, 1.45312169e+03, 1.46506693e+03, 1.53732757e+03,
       1.44767229e+03, 1.44767229e+03, 1.32344523e+03, 1.27900791e+03,
       1.04405187e+03, 1.44767229e+03, 3.97501178e+02, 4.77692229e+03,
       1.47003873e+03, 1.42766338e+03, 8.91783976e+02, 1.44767229e+03,
       1.35659372e+03, 1.43773029e+03, 1.16061336e+03, 1.17627837e+03,
       3.43468122e+02, 1.28767814e+03, 1.45958122e+03, 1.44767229e+03,
       1.44767229e+03, 1.50884562e+03, 1.19452381e+01, 8.42058747e+01,
       5.44940476e+00, 5.44940476e+00, 1.29676463e+02, 1.74113780e+02,
       4.09069821e+02, 5.44940476e+00, 1.05562052e+03, 3.32380060e+03,
       1.69170339e+01, 2.54583135e+01, 5.61337718e+02, 5.44940476e+00,
       9.65279762e+01, 1.53914048e+01, 2.92508333e+02, 2.76843326e+02,
       1.10965357e+03, 1.65443554e+02, 6.45952381e+00, 5.44940476e+00,
       5.44940476e+00, 5.57239286e+01, 7.22606366e+01, 1.73946429e+01,
       1.73946429e+01, 1.41621701e+02, 1.86059018e+02, 4.21015060e+02,
       1.73946429e+01, 1.06756575e+03, 3.31185536e+03, 4.97179576e+00,
       3.74035516e+01, 5.73282956e+02, 1.73946429e+01, 1.08473214e+02,
       2.73366429e+01, 3.04453571e+02, 2.88788564e+02, 1.12159881e+03,
       1.77388793e+02, 5.48571429e+00, 1.73946429e+01, 1.73946429e+01,
       4.37786905e+01, 8.96552795e+01, 8.96552795e+01, 2.13882338e+02,
       2.58319655e+02, 4.93275696e+02, 8.96552795e+01, 1.13982639e+03,
       3.23959472e+03, 6.72888409e+01, 1.09664188e+02, 6.45543592e+02,
       8.96552795e+01, 1.80733851e+02, 9.95972795e+01, 3.76714208e+02,
       3.61049201e+02, 1.19385945e+03, 2.49649429e+02, 7.77463509e+01,
       8.96552795e+01, 8.96552795e+01, 2.84819462e+01, 0.00000000e+00,
       1.24227058e+02, 1.68664375e+02, 4.03620417e+02, 0.00000000e+00,
       1.05017111e+03, 3.32925000e+03, 2.23664386e+01, 2.00089087e+01,
       5.55888313e+02, 0.00000000e+00, 9.10785714e+01, 9.94200000e+00,
       2.87058929e+02, 2.71393921e+02, 1.10420417e+03, 1.59994150e+02,
       1.19089286e+01, 0.00000000e+00, 0.00000000e+00, 6.11733333e+01,
       1.24227058e+02, 1.68664375e+02, 4.03620417e+02, 0.00000000e+00,
       1.05017111e+03, 3.32925000e+03, 2.23664386e+01, 2.00089087e+01,
       5.55888313e+02, 0.00000000e+00, 9.10785714e+01, 9.94200000e+00,
       2.87058929e+02, 2.71393921e+02, 1.10420417e+03, 1.59994150e+02,
       1.19089286e+01, 0.00000000e+00, 0.00000000e+00, 6.11733333e+01,
       4.44373170e+01, 2.79393359e+02, 1.24227058e+02, 9.25944053e+02,
       3.45347706e+03, 1.46593497e+02, 1.04218149e+02, 4.31661255e+02,
       1.24227058e+02, 3.31484866e+01, 1.14285058e+02, 1.62831871e+02,
       1.47166863e+02, 9.79977109e+02, 3.57670916e+01, 1.36135987e+02,
       1.24227058e+02, 1.24227058e+02, 1.85400391e+02, 2.34956042e+02,
       1.68664375e+02, 8.81506736e+02, 3.49791437e+03, 1.91030814e+02,
       1.48655466e+02, 3.87223938e+02, 1.68664375e+02, 7.75858036e+01,
       1.58722375e+02, 1.18394554e+02, 1.02729546e+02, 9.35539792e+02,
       8.67022534e+00, 1.80573304e+02, 1.68664375e+02, 1.68664375e+02,
       2.29837708e+02, 4.03620417e+02, 6.46550694e+02, 3.73287042e+03,
       4.25986855e+02, 3.83611508e+02, 1.52267896e+02, 4.03620417e+02,
       3.12541845e+02, 3.93678417e+02, 1.16561488e+02, 1.32226495e+02,
       7.00583750e+02, 2.43626267e+02, 4.15529345e+02, 4.03620417e+02,
       4.03620417e+02, 4.64793750e+02, 1.05017111e+03, 3.32925000e+03,
       2.23664386e+01, 2.00089087e+01, 5.55888313e+02, 0.00000000e+00,
       9.10785714e+01, 9.94200000e+00, 2.87058929e+02, 2.71393921e+02,
       1.10420417e+03, 1.59994150e+02, 1.19089286e+01, 0.00000000e+00,
       0.00000000e+00, 6.11733333e+01, 4.37942111e+03, 1.07253755e+03,
       1.03016220e+03, 4.94282798e+02, 1.05017111e+03, 9.59092540e+02,
       1.04022911e+03, 7.63112183e+02, 7.78777190e+02, 5.40330556e+01,
       8.90176961e+02, 1.06208004e+03, 1.05017111e+03, 1.05017111e+03,
       1.11134444e+03, 3.30688356e+03, 3.34925891e+03, 3.88513831e+03,
       3.32925000e+03, 3.42032857e+03, 3.33919200e+03, 3.61630893e+03,
       3.60064392e+03, 4.43345417e+03, 3.48924415e+03, 3.31734107e+03,
       3.32925000e+03, 3.32925000e+03, 3.26807667e+03, 4.23753474e+01,
       5.78254752e+02, 2.23664386e+01, 1.13445010e+02, 3.23084386e+01,
       3.09425367e+02, 2.93760360e+02, 1.12657061e+03, 1.82360588e+02,
       1.04575100e+01, 2.23664386e+01, 2.23664386e+01, 3.88068947e+01,
       5.35879404e+02, 2.00089087e+01, 7.10696627e+01, 1.00669087e+01,
       2.67050020e+02, 2.51385013e+02, 1.08419526e+03, 1.39985241e+02,
       3.19178373e+01, 2.00089087e+01, 2.00089087e+01, 8.11822421e+01,
       5.55888313e+02, 4.64809741e+02, 5.45946313e+02, 2.68829384e+02,
       2.84494392e+02, 5.48315854e+02, 3.95894163e+02, 5.67797241e+02,
       5.55888313e+02, 5.55888313e+02, 6.17061646e+02, 9.10785714e+01,
       9.94200000e+00, 2.87058929e+02, 2.71393921e+02, 1.10420417e+03,
       1.59994150e+02, 1.19089286e+01, 0.00000000e+00, 0.00000000e+00,
       6.11733333e+01, 8.11365714e+01, 1.95980357e+02, 1.80315350e+02,
       1.01312560e+03, 6.89155782e+01, 1.02987500e+02, 9.10785714e+01,
       9.10785714e+01, 1.52251905e+02, 2.77116929e+02, 2.61451921e+02,
       1.09426217e+03, 1.50052150e+02, 2.18509286e+01, 9.94200000e+00,
       9.94200000e+00, 7.11153333e+01, 1.56650073e+01, 8.17145238e+02,
       1.27064779e+02, 2.98967857e+02, 2.87058929e+02, 2.87058929e+02,
       3.48232262e+02, 8.32810245e+02, 1.11399772e+02, 2.83302850e+02,
       2.71393921e+02, 2.71393921e+02, 3.32567255e+02, 9.44210017e+02,
       1.11611310e+03, 1.10420417e+03, 1.10420417e+03, 1.16537750e+03,
       1.71903078e+02, 1.59994150e+02, 1.59994150e+02, 2.21167483e+02,
       1.19089286e+01, 1.19089286e+01, 4.92644048e+01, 0.00000000e+00,
       6.11733333e+01, 6.11733333e+01])

#### DIFFERENCES

In [67]:
CoeffDif = abs(regsDur - regs)
CoeffDif

197      [5517.866666666667]
508      [325.5950270270271]
515      [1447.949397590361]
516      [5.413690476190477]
517     [17.358928571428592]
638       [89.3695652173913]
661                    [0.0]
677                    [0.0]
1230    [134.22705802968954]
1237    [168.12866071428573]
1361    [403.58470238095214]
1404                   [0.0]
1407    [1052.5711111111111]
1415    [3330.2499999999977]
1607    [22.949771953374444]
1609     [19.72319444444446]
1621     [556.2311700680273]
1651                   [0.0]
1652     [90.93571428571417]
1698                [11.742]
1722      [286.878804347826]
1780    [270.57885273972613]
1786    [1105.2041666666662]
1797    [159.95843537414973]
1900    [13.808928571428572]
1979                   [0.0]
2258                   [0.0]
2487    [60.673333333333304]
dtype: object

#### MULTIVARIATE

In [68]:
import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.multivariate.multivariate_ols import _MultivariateOLS

In [69]:
for i in range(len(regDur)):
    x = []
    y = []
    y2 = []
    for j in range(len(regDur.iloc[i])):     
        x.append(day_map[regDur.iloc[i][j][0]])
        y.append(regDur.iloc[i][j][1])
        y2.append(reg.iloc[i][j][1])
    if len(x) < 2:
        continue
    df = pd.DataFrame({
        'x':x,
        'y1':y,
        'y2':y2
    })
    Y = df[['y1','y2']]
    #X = sm.add_constant(df[['x']])
    X = np.array(df['x']).reshape(-1,1)
    model = _MultivariateOLS(Y, X)
    result = model.fit()
    "print(result.mv_test((('x', [[0, 1]]), None)))

SyntaxError: unterminated string literal (detected at line 21) (3945861338.py, line 21)